Map<String, String> englishText = {

//---- No Internet Screen ----
 "errortitle" : "No Internet Connection",
 "errordesc" : "Please connect to the internet and try again",
 "tryagainbtn" : "TRY AGAIN",

  //Login Screen
  'railname':'Railway',
  'unitname':'Unit Details',
  'department':'Department',
  'department1':'Select Department',
  'consignee':'Consignee',
  'payauth':'Paying Authority',
  'openbal':'Opening Balance',
  'billreceived':'Bills Received',
  'billreturned':'Bills Returned',
  'billpassed':'Bills Passed',
  'totalpending':'Pending Bills',
  'tttle':'Break-up of Pending Bills',
  'pendsevendays':'< 7 Days',
  'pendfifteendays':'7 to 15 Days',
  'pendthirtydays':'15 to 30 Days',
  'pendmorethirty':'>30 Days',
  'userId': 'User ID',
  'emailId': 'Email ID',
  'enterPin': 'Enter PIN',
  'saveCred': 'Save Credentials for 05 Days',
  'login': 'Login',
  'enableAccessLabel1': 'How to ',
  'enableAccessLabel2': 'enable login ',
  'enableAccessLabel3': 'access for UDM App',
  'resetPinInstructionsLabel1': 'How to ',
  'resetPinInstructionsLabel2': 'Reset PIN',
  'loginScreenInstructions1': 'Login to www.ireps.gov.in',
  'loginScreenInstructions2': 'Click on switch icon on right side upper corner',
  'enableAccessInstructionsTitle': 'To enable login access for UDM',
  'enableAccessInstructionsText':
  'Click on ‘Enable Mobile Access’ and complete the process',
  'resetPinInstructionsTitle': 'To reset PIN for UDM',
  'resetPinInstructionsText': 'Click on ‘Reset APP PIN’ and complete the process',
  'validEmail' : 'Please enter valid Email-ID',
  //Home Screen
  'udmFull': 'User Depot Module',
  'udmtitle' : 'User Depot Module(UDM)',
  'irepslabel' : 'IREPS',
  'udmlabel' : 'UDM',
  'welcome': 'Welcome',
  'home' : 'Home',
  'profile' : 'Profile',
  'settings' : 'Settings',
  //Change PIN
  'changePin': 'Change PIN',
  'confirmPin': 'Confirm New PIN',
  'enterOldPin': 'Enter Old PIN',
  'enterNewPin': 'Enter New PIN',
  'confirm':'Confirm',
  'cancel':'Cancel',
  'logout' : 'Logout',
  'logOut':'Logout from this device?',
  'changeLogin':'Change Login',
  'rateUs': 'Rate Us',
  'version': 'Version',
  //Profile
  'profile': 'Profile',
  'userDetails': 'User Details',
  'orgDetails': 'Organisation Details',
  'lastLogin': 'Last Login Time',
  'lastSignin': 'Last Signin Time',
  //Search Item
  'searchItem': 'Search Item',
  'on-lineBillSummary' : 'On-Line Bill Summary',
  'reset': 'Reset',
  'submit': 'Submit',
  'pinLengthError': 'Please enter 6-12 digit PIN',
  'railway': 'Railway',
  'consignee': 'Consignee',
  'payingauthorityrailway': 'Paying Authority Railway',
  'consigneerailway': 'Consignee Railway',
  'unitType': 'Unit Type',
  'unitName': 'Unit Name',
  'departmentName': 'Department Name',
  'selectdepartment': 'Select Department',
  'userDepot': 'User Depot',
  'selectuserdepot': 'Select User Depot',
  'payauth': 'Paying Authority',
  'payauth1': 'All',
  'checkconnection' : 'Please check your internet connection!!',

  'consigneedetais1': 'Consignee Details',
  'consigneedetails': 'Consignee Details',
  'getDetails': 'Get Details',
  'plNo': 'PL No',
  'description': 'Description',
  'plNoDisplayText': 'Enter PL/ minimum 3 letters of description',
  'plNoErrorText': 'Value needs to be more than 3 characters',
  'entersearchcriteria': 'Value needs to be more than 3 characters',
  //Item List
  'department': 'Department',
  'itemList': 'Item List',
  'billstatus': 'Bill Status',
  'totalCount': 'Total Count',
  'pl/itemCode': 'PL No./Item Code',
  'ledgerName': 'Ledger Name',
  'ledgerNo': 'Ledger No.',
  'ledgerFolioNo': 'Ledger Folio No.',
  'itemCategory': 'Item Category',
  'itemDescription': 'Item Description',
  //'itemDescription1': 'Item Description',
  'consigneeCode': 'Consignee Code',
  'consigneeDepot': 'Consignee Depot',
  'lastReceipt': 'Last Receipt',
  'issueDate': 'Issue Date',
  'stock': 'Stock',
  'averageRateRs': 'Average Rate (Rs.)',
  'valueRs': 'Value (Rs.)',
  'aac': 'AAC',
  'aacncp' : 'AAC AAC NCP',
  'briefDescription': 'Brief Description',
  'summary': 'Summary',
  'recordFound': 'Record Found',
  'more': 'More',
  'less': 'Less',
  'totalQuantity': 'Total Qty.',
  'quantity': 'Qty.',
  'unit': 'Unit',
  'totalVal': 'Total Value (Rs.)',
  'rate': 'Rate',
  //User Depot Details
  'userDepotDetails': 'User Depot Details',
  'status':'Status of on-Line submitted Bills',
  'consname' : 'Consignee Details',
  'consrly': 'Consignee Railway',
  //'podate': 'PO Date',
  'ponumber': 'PO No and Date',
  'posr': 'PO SI. No.',
  'saveContact': 'Save Contact',
  'overallDetailsHeading': 'Details of Overall-in-charge',

  //Stock Availability
  'stockAvailability': 'Stock Availability',
  'userSubDepot': 'User Sub Depot',
  'userSubDepot1': 'Sub Consignee',
  'userSubDepot2': 'Select User Depot',
  'selectReportCriteria': 'Select Report Criteria',
  'selectStockAvailability': 'Select Stock Availability',
  'aacBasis': 'AAC Basis',
  'thresholdLimitBasis': 'Threshold Limit Basis',
  'greaterThan': 'Greater than',
  'lessThan': 'Less than',
  'monthsBasedOnAAC': 'Months based on AAC',
  'itemType': 'Item Type',
  'itemUsage': 'Item Usage',
  'stockNonStock': 'Stock/Non-Stock',
  'times': 'Times',
  'thresholdLimit': 'Threshold Limit',

  //Stores Depot Stock
  'storesDepotStockList': 'Stores Depot Stock List',
  'storesDepotStock': 'Stores Depot Stock',
  'onlinebillstatus': 'On-Line Bill Status',
  'storesDepot': 'Stores Depot',
  'stockSummary': 'Summary of Stock',
  'ward': 'Ward',
  'nonMovingItems': 'Non-Moving Items',
  'rateRs': 'Rate (Rs.)',
  'valueWiseStock': 'Value-Wise Stock',
  'stockQty/Unit': 'Stock Qty. / Unit',
  'highValueItems': 'High Value Items',
  'pl/min3Desc': 'Enter PL/ minimum 3 character of Description',
  'consAnalysis': 'Consumption Analysis',

  'consSummary': 'Consumption Summary',

  'transaction': 'Transactions',
  'receipt': 'Receipt',

  'poSearch': 'PO Search',

  //Search PO
  'PONo': 'PO No.',
  'enterPONo': 'Enter PO No.',
  'vendorName': 'Vendor Name',
  'entersearchcriteria': 'Enter Search Criteria',
  'searchcriteria': 'Enter PO No./Vendor Name/Description',
  'enterVendorName': 'Enter Vendor Name',
  'POPlacingAuthority': 'PO Placing Authority',
  'coverageStatus': 'Coverage Status',
  'PODateFrom': 'PO Date: From',
  'billsubmissiondatefrom': 'Bill Submission Date : From',
  'billsubmissiondateto': 'Bill Submission Date : To',
  'PODateTo': 'PO Date: To',
  'purchaseSection': 'Purchase Section',
  'tenderType': 'Tender Type',
  'inspectionAgency': 'Inspection Agency',
  'industryType': 'Industry Type',
  'POType': 'PO Type',
  'POValue': 'PO Value',
  'enterPODateFrom': 'Enter PO Date: From',
  'enterPODateTo': 'Enter PO Date: To',
  'pleaseSelectDatesTo': 'please select dates to keep search period within 3 months',
  'itemDescriptionWarning': 'Item Description must be greater than three character',
  'descpowarning' : 'Please enter 3 characters of item description OR Po No.',
  'itemdescription':'Item Description',
  'accountname': 'Vendor Name',
  'POValueFrom': 'PO Value(Rs.): From',
  'POValueTo': 'PO Value(Rs.): To',
  'POValueFromHint': 'Enter PO Value(Rs.): From',
  'POValueToHint': 'Enter PO Value(Rs.): To',
  'noDataFound': 'No data found',
  'searchWithSameInput': 'Search with same input for 12 months period backwards?',
  'yes': 'Yes',
  'no': 'No',
  'PONoAndDate': 'PO No.& Date',
  'code': 'Code',
  'POSrNo': 'PO Sr. No.',
  'PLNo': 'PL No.',
  'itemQuantity': 'Item Quantity',
  'deliveryDate': 'Delivery Date',
  'itemUnitRate': 'Item Unit Rate (Rs.)',
  'itemValue': 'Item Value',
  'quantityReceived': 'Quantity Received',
  'paidValue': 'Paid Value (Rs.)',
  'stockingStoreDepot':'Stocking Stores Depot',

  //PO search action
  'viewContactDetails': 'View Contact Details',
  'vendorCode': 'Vendor Code',

  //Summary of Stock
  'summaryOfStock': 'Summary of Stock',
  'userDepotStockSummary': 'User Depot Stock Summary',

  //Non-Moving Items
  'months': 'month\'s',
  'itemNotIssuedSince1Month': 'item not issued since last 1 month',
  'usage': 'Usage',
  'type': 'Type',
  'category': 'Category',

  //Value-Wise Stock
  'valueInRsDefinedByUser': 'Value (in Rs.) defined by User',

  //High Value Items
  'top': 'Top',
  'highValueItemsAsPerStockValue': 'High Value Items (as per Stock Value)',

  //Consumption Analysis
  'currentPeriod': 'Current Period',
  'previousPeriod': 'Previous Period',
  'from': 'From',
  'to': 'To',
  'percentageChange': 'Percentage Change',
  'by': 'By',
  'increase': 'Increase (+)',
  'decrease': 'Decrease (-)',
  'consAnalysis':'Consumption Analysis Items',
  'avgMonthlyConsCurrentP':'Avg. Monthly Consumption in Current period',
  'avgMonthlyConsPreP':'Avg. Monthly Consumption in Previous period',


  // Consumption Summary
  'chooseSummaryType': 'Choose Summary Type',
  'topNHighConsumptionValueItems': "Top 'N' High Consumption Value Items",
  'itemsHavingConsumptionValueAboveSpecifiedLimit':
  'Items having Consumption Value above specified Limit',
  'consumptionComparisonWithAAC': 'Consumption comparison with AAC',
  'specifyNNoOfTop': "Specify 'N' No. of Top High Value Items",
  'specifyLimitOfConVal': 'Specify Limit of Consumption Value (in Rs.)',
  'percentageGreater': 'Percent Greater than (>)',
  'percentageLess': 'Percent Less than (<=)',
  'proportionateQtyAsPerAAC': 'Proportionate Quantity as per AAC',
  'consumptionSummary': 'Consumption Summary',
  'consumptionVal': 'Consumption Value (Rs.)',
  'consumptionQty': 'Consumption Qty.',

  //Transaction Search
  'searchPLItemFolioDesc': 'Search PL/Item/Folio/Description',
  'searchPLItemFolioDescHint':
  'Search PL No / Item Code / Folio Name / Description',
  'ledgerFolioPlNo': 'Ledger Folio PL No.',
  'folioNo': 'Folio No.',
  'fromDate': 'From Date',
  'fromDate1': 'Receipt Date : From',
  'podatefrom': 'PO Date : From',
  'toDate': 'To Date',
  'toDate1': 'Receipt Date : To',
  'podateto': 'PO Date : To',

  //Transaction Summary
  'transactionSummary': 'Transaction Summary',
  'details': 'Details',
  'date': 'Date',
  'noDateOfReceipt': 'No. & Date of \nReceipt/Issue',
  'myNameIs': 'My name is ',
  'receiptQuantity': 'Recepit Quantity',
  'issueQuantity': 'Issue Quantity',
  'balanceQuantity': 'Balance Quantity',
  'initials': 'Initials',
  'remarks': 'Remarks',
  'receivedFromIssuedTo': 'Received From/Issued to: ',
  'transactionDetailsFor': 'Transaction Details for the period:',
  'folioName': 'Folio Name',
  'nameOfArticleItem': 'Name of Article/Item',
  'unitWeight': 'Unit Weight (in kg)',
  'existingThresholdUnit': 'Existing Threshold Unit',
  'ledger': 'Ledger',
  'transactionUnit': 'Transaction Unit',
  'recepitsDuringSelectedPeriod': 'Receipts During the selected Period: ',
  'issueDuringSelectedPeriod': 'Issue During the selected Period',
  'balanceAtEndOfPeriod': 'Balance at the end of selected period',
  'currentClosingBalance': 'Current Closing Balance',
  'currentClosingBalanceValue': 'Current Closing Balance\nValue (in Rs.)',
  'averageRate': 'Average Rate Rs.',
  'itemDetails':'Item Details',
  'itemSummary':'Item Summary',
  'consignee':'Consignee',
  'subDepot':'Sub Depot',
  'plItemCode':'PL No./Item Code',
  //MISC
  'jumpButton': 'Jump Buttons',
  'jumpButtonDesc': 'Tap these to jump up and down 20 items',
  'select': 'Select',
  'totalloanreceipt': 'Balance Loan to Return',
  'totalloanissue': 'Balance Loan to Receive',
  'whatsAppMsg': 'WhatsApp msg',
  'failedToLaunchWA': 'Failed to launch WhatsApp',
  //Item receipt details
  'itemReceiptDetails': 'Item Receipt Details',
  'cdCode': 'CD Code',
  'receivingDepot': 'Receiving Depot',
  'subDepot': 'Sub Depot',
  'plNoOfMaterial': 'PL No. of material received',
  'demandAndIssueDetails': 'Demand and Issue Details',
  'demandNo': 'Demand No.',
  'demandDate': 'Demand Date',
  'issueNoteNo': 'Issue Note No.',
  'issueDepotShop': 'Issuing Depot / Shop',
  'issuingOfficial': 'Issuing Official',
  'allocationDetails': 'Allocation Details',
  'allocationPGR': 'Allocation P/G/R/\nOrder No.',
  'workOrderNo': 'Work Order No.',
  'voucherDetails': 'Voucher Details',
  'voucherNo': 'Voucher No.',
  'voucherDate': 'Voucher Date',
  'descriptionTabs': '\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t',
  'remarksTabs': '\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t',
  //Advice Note
  'adviceNote': 'Advice Note',
  'dpcd': 'DPCD',
  'consignor': 'Consignor',
  'controllingOfficer': 'Controlling Officer',
  'allocationNo': 'Allocation No.',
  'rmcCreditNote': 'RMC / Credit Note No.',
  'rmcCreditDate': 'RMC / Credit date',
  'wagonNo': 'Wagon No.',
  'rrNo': 'RR No.',
  'wagonDate': 'Wagon Date',
  'depotRemarks': 'Depot Remarks',
  'dispatchDetails': 'Dispatch Details',
  'approvingAuthority': 'Approving Authority',
  'accountalDetails': 'Accountal Details',
  'returningOfficial': 'Returning Official',
  'receivingDate': 'Receiving Date',
  'officialDetails': 'Official Details',
  'issuingDepot': 'Issuing Depot',
  'quantityInWords': 'Quantity In Words',
  'sign': 'Sign',
  'depotShopCodeConsignee': 'Depot / Shop Code / Consignee / Contractor',
  'detailsOfReceiptVoucher': 'Details of Receipt Voucher',
  //Issue Note
  'issueNote': 'Issue Note',
  'issueAndDemandDetails': 'Issue and Demand Details',
  //Warranty Claim For Rejected Item
  'depotLodgingWarranty': 'Depot Lodging Warranty Claim',
  'warrantyClaimNo': 'Warranty Claim No.',
  'warrantyClaimDate': 'Warranty Claim Date',
  'poContractNo': 'PO Contract No.',
  'poContractDate': 'PO Contract Date',
  'depotOriginallyReceivingMaterial': 'Depot Originally Receiving Material',
  'subDepotSubConsignee': 'Sub-Depot /\nSub-Consignee',
  'warrantyClaim': 'Warranty Claim Details',
  'nameAndAddressOfSupplier': 'Name and Address of Supplier',
  'challanNoDate': 'Challan No. /\nDate',
  'billNoDate': 'Bill No. /\nDate',
  'ddrNoDate': 'DDR No. /\nDate',
  'islNoDate': 'ISL No. /\nDate',
  'inspectionBy': 'Inspection By',
  'qtyRejectedUnderWarranty': 'Quantity Rejected Under Warranty',
  'qtyRejectedUnderWarrantyWords':
  'Quantity Rejected Under Warranty (in Words)',
  'ratePerUnit': 'Rate / Unit',
  'valueOfRejectedItem': 'Value of Rejected Item',
  'headPerAllocation': 'Head / Allocation',
  'warrantyClaimAmount': 'Warranty Claim Amount',
  'recoveryAdvice': 'Recovery Advice',
  'note': 'Note',
  'accountingUnit': 'Accounting Unit',
  'warrantyDetails': 'Warranty Details',
  //Consignee Receipt Note
  'crnNo': 'CRN No.',
  'firmDetails': 'Firm\'s Details',
  'dmtrNo': 'DMTR No.',
  'packagesReceived': 'Packages Received',
  'poContractUnitRate': 'PO/Contract Unit Rate (All Incl.)',
  'itemQtyInPO': 'Item\'s qty in PO/Contract',
  'deliveryPeriod': 'Delivery Period',
  'qtyDisp': 'Quantity Dispached \n(in PO/Contract Unit)',
  'qtyAcceptPO': 'Quantity Accepted \n(in PO/Contract Unit)',
  'qtyAcceptTU': 'Quantity Accepted \n(in Transaction Units)',
  'qtyRecPO': 'Quantity Received \n(in PO/Contract Unit)',
  'qtyRejPO': 'Quantity Rejected \n(in PO/Contract Unit)',
  'acceptedQtyVal': 'Value of accepted Qty \n(in Rs.)',
  'demandAndIssue': 'Demand and Issue Details',
  'demandWorkSanction': 'Demand/Work Sanction No. & \nDate',
  'challanDate': 'Challan No. & \nDate',
  'icDate': 'IC No. \n/Date',
  'productSLDate': 'Product SL No.',
  'receivingOfficial': 'Receiving Official',
  'billingDetails': 'Billing Details',
  'billPassing': 'Bill Passing',
  'allocation': 'Allocation',
  'locationOfMatDuringRec': 'Location of Material during Receipt',
  'makeBrand': 'Make/Brand',
  'accountedInLedger': 'Accounted for in Ledger',
  'payingAuthority': 'Paying Authority',
  'poContractAgency': 'PO/Contract Inspection Agency',
  'paymentTerms': 'Payment Terms:',
  'dateOfAccountal': 'Date of Accountal',
  'matStockLoc': 'Material Stocking Location',
  'ledgerFolio': 'Ledger Folio',
  'somethingWentWrong': 'Something Went Wrong',
  'signatureOfStockHolder': 'Signature Of Stock Holder',
  'crnsummary': 'CRN Summary',

  //online status action page
  'qty': 'Qty.',
  'qty1': '',
  'payingrly': 'Consignee Railway',

  'consrly': 'Consignee Railway',
  'Consignee Code': 'Consignee Code',
  'poNO': 'PO No.& Date',
  'podate': '',
  'vendorname': 'Vendor Name',
  'poSiNo': 'PO Sl.No.',
  'itemdesc1': 'Item Description',
  'doctype': 'Doc.Type/                     (CRC/CRN/RNote)',
  'dmtrno': 'DMTR/RO No.& Date',
  'dmtrno1': '',
  'allocation': 'Paying Railway',
  'payingauthority': 'Paying Authority',
  'billno': 'Bill No.& Date',
  'billno1': '',
  'billdate': 'IREPS Bill No.& Date',
  'billdate1': '',
  'billtype': 'Bill Type',
  'paymenttype': 'Payment Type',
  'paymentpercentage': 'Payment Percentage',
  'itemno': 'Item No.of Bill',
  'billamt': 'Bill Amt for Item (Rs.)',
  'co6no': 'CO6 No.& Date',
  'co6date': '',
  'co7no': 'CO7 No.& Date',
  'co7date': '',
  'passedamtitem': 'Passed Amt for Item (Rs.)',
  'paydate': 'Payment Date',
  'tbillamt': 'Total Bill Amt (Rs.)',
  'passedmtbill': 'Passed Amt for Bill (Rs.)',
  'deductedamtbill': 'Deducted Amt for Bill (Rs.)',
  'paidamtbill': 'Paid Amt for Bill (Rs.)',
  'returnreason': 'Return Reason',
  'returndate': 'Return Date',
  'payrly': 'Paying Railway',
  'rly': 'Railway',
  'frombill':  'From Bill',
  'co6status':  'Co6 Status',
  'payauth1':  'All',
  'rnotedate':  'RNote Date',
  'rnoteno' :  'RNote No',
  'plNoErrorText1' : 'Please enter search criteria',

  'railname': 'Railway',
  'unit': 'Unit Type',
  'uname': 'Unit Name',
  'department': 'Department',
  'consignee': 'Consignee',
  'pono&date': 'PO No. & Date',
  'itemdes': 'Description',
  'dtype': 'Doc. Type',
  'docnodate': 'Doc. No. & Date',
  'billnodate': 'Bill No. & Date',
  'irepsbillnodate': 'IREPS Bill No. & Date',
  'irepsbillsrno': 'IREPS Bill Sr. No.',
  'billamt1': 'Bill Amt.',
  'billsubdate': 'Bill Submission Date: From',
  'billsubdateto': 'Bill Submission Date: To',

  //CRN Digitally-signed
  'crndigisigned' : 'CRN (Digitally Signed)',
  'awaitingmyapproval' : 'Await my approval',
  'datefrom' : 'From Date',
  'dateto' : 'To Date',
  'search' : 'Search',
  'dropremarks' : 'Drop Remarks',
  'foewardedby' : 'Forwarded by',
  'myforwarded' : 'My Forwarded',
  'myfinalised' : 'My Finalized Cases',
  'finalisedbyon' : 'Finalized by/on',
  'forwardedtoon' : 'Forwarded to/on',

  //CRC Digitally-signed
  'crcdigisigned' : 'CRC (Digitally-signed)',
  'datefrom' : 'From Date',
  'dateto' : 'To Date',
  'search' : 'Search',
  'awaitingapproval' : 'Awaiting my Approval',
  'finalizedme' : 'Finalized by me',
  'forwardedfrom' : 'Forwarded From',
  'vouchernumdate' : 'Voucher No. & Date',
  'ponumdate' : 'PO No. & Date',
  'plnumitemcode' : 'PL No./Item Code',
  'vendorname' : 'Vendor Name',
  'itemdesc' : 'Item Description',
  'recdqty' : 'Recd. Qty.',
  'recdvalue' : 'Recd. Value(Rs.)',
  'acceptqty' : 'Accept Qty.',
  'acceptvalue' : 'Accept Value(Rs.)',
  'dropremarks' : 'Drop Remarks',
  'status' : 'Status',
  'action' : 'Action',
  'finalisedbyon' : 'Finalized by/on',
  'forwardedtoon' : 'Forwarded to/on',

  // Stock item history sheet
  'stkitemtitle' : 'Stock Item History Sheet',
  'tophead' : 'Item Position (History Sheet) of Stock Item',
  'rly' : 'Railway:',
  'selectrly' : '--Select Railway--',
  'selectcon' : '--Select Consignee--',
  'selectunittype' : '--Select Unit Type--',
  'selectunitname' : '--Select Unit Name--',
  'pldetails' : 'PL Details:',
  'hsmrly' : 'History Sheet(My Rly)',
  'hsarly' : 'History Sheet(All Rly)',
  'clear' : 'Clear',
  'exit' : 'Exit',
  'find' : 'Find',
  'plhint' : 'Type PL/Few characters of Item description to search',
  'rlysuggestion' : 'Please select a railway to find history sheet',
  'plsuggestion' : 'Please type pl details to find history sheet',
  'messagemyrly' : 'Already data showing of My Railway',
  'mesaageallrly' : 'Already data showing of All Railway',
  'dnf' : 'Data not found',
  'searchbtn' : 'Search',
  'search' : 'Search...',
  'plno' : 'PL No.',
  'desc' : 'Description',

  'historysheet' : 'History Sheet',

  'uncovereddue' : 'UN-COVERED DUES DETAILS',
  'depot' : 'Depot',
  'demandnum' : 'Demand No.',
  'regdate' : 'Reg. Date',
  'dueqty' : 'Due Qty',
  'unit' : 'UNIT',
  'type' : 'Type',
  'duedate' : 'Due Date',
  'filetendernum' : 'File/Tender No.',
  'remarks' : 'Remarks',

  'rlyboardintent' : 'RLY.BOARD INDENT COVERAGE DETAILS',
  'ponumname' : 'P.O.No./Vendor Name',
  'sr' : 'Sr',
  'depot' : 'Depot',
  'airate' : 'AI Rate',
  'poqty' : 'PO Qty',
  'unit' : 'UNIT',
  'dueqty' : 'Due Qty',
  'startdp' : 'Start DP',
  'delydt' : 'Dely. Dt',
  'demnum' : 'Dem. No.',

  'covereddue' : 'COVERED DUES DETAILS',

  'totalavl' : 'Total available Stock of selected item in Digital Ledgers maintained by Users/Consignees of in UDM',

  'accmaterialdetail' : 'DETAILS OF MATERIAL UNDER ACCOUNTAL',
  'srnum' : 'Sr.',
  'recieptdet' : 'Receipt Details',
  'rejectdtl' : 'Rejection Detail',
  'orderlastfiveryears' : 'ORDERS PLACED DURING LAST 5 YEARS',

  'cancqty' : 'Canc Qty	',

  'cancqty' : 'Canc Qty',
  'rejqty' : 'Rej. Qty',
  'recqty' : 'Recd Qty',
  'orgdp' :  'Org.DP',
  'startdp' : 'Start DP',
  'extdp' : 'Ext.DP',
  'postatus' : 'PO Status',

  'overstock' : 'OVER-STOCK/SURPLUS/INACTIVE IN OTHER RAILWAY',
  'ward' : 'Ward',

  'plnum' : 'P.L No.',
  'oldplnum' : 'Old Pl No.',
  'desc' : 'Description',
  'uniplnum' : 'Uni. Pl No.',
  'uniyn' : 'Uni_YN',
  'sec' : 'Sec',
  'file' : 'FILE',
  'cp' : 'CP',
  'srs' : 'SRS',
  'vitsaf' : 'Vit/Saf',
  'abc' : 'ABC',
  'pasnct' : 'PAS.NCT',
  'mustchg' : 'MUST.CHG',
  'self' : 'SHELF',
  'source' : 'SOURCE',
  'unfrly' : 'UNF.RLY',
  'wtkg' : 'Wt KG',

  'intentdetail' : 'Intent Detail',
  'intentpurnum' : 'Indent No./Pur.Agency',
  'indqty' : 'Ind Qty',
  'unit' : 'UNIT',
  'cvdqty' : 'Cvd Qty',
  'delydt' : 'Dely.Dt',
  'dueqty' : 'Due Qty',

  'coveredduedetail' : 'COVERED DUES DETAILS',

  'matunderacc' : 'DETAILS OF MATERIAL UNDER ACCOUNTAL',
  'recdet' : 'Receipt Details',

  'materialrejected' : 'Details of Material Rejected',


//==============challan payment details=======================
  'paymentchallan': '	Challan Payment Details',

  //================poserachrecipt/issue==================


  'receipt' : 'Receipt Details',
  'totalqtydis' : 'Total Qty. Dispatched',
  'tqtyrecieved': 'Total Qty. Received',
  'tqtyaccepted': 'Total Qty. Accepted',
  'tqtyrejeted': 'Total Qty. Rejected',
  'twtyrejection': 'Total Warranty Rejection',
  'initialrejection': 'Initial Rejected Qty. Accepted in Re-Inspection ',
  'warrantyrejection': 'Warranty Rejected Qty. Accepted in Re-Inspection ',
  'DMTR No. & Date': 'DMTR No. & Date',
  'Challan No. & Date': 'Challan No. & Date',
  'Make / Brand': 'Make / Brand',
  'Product Sr. No.': 'Product Sr. No.',
  'Warranty upto': 'Warranty upto',
  'Qty. Dispatched': 'Qty. Dispatched',
  'QtyReceived': 'Qty. Received',
  'Qty. Accepted': 'Qty. Accepted',
  'Initial Rejection': 'Initial Rejection',
  'Warranty Rejection': 'Warranty Rejection',
  'Re-Insp. Qty': 'Re-Insp. Qty',
  'Returned Qty. to Vendor': 'Returned Qty. to Vendor',
  'Qty. taken into Ledger': 'Qty. taken into Ledger',
  'Transaction Status': 'Transaction Status',
  'Action': 'Action',
  'Purchase Order / Contract Supply Status': 'Purchase Order / Contract Supply Status',
  'Railway': 'Railway',
  'Consignee Code': 'Consignee Code',
  'PO / Contract No.': 'PO / Contract No.',
  'PO / Contract Date': 'PO / Contract Date',
  'Item Sl. No. in PO / Contract': 'Item Sl. No. in PO / Contract',
  'Item Description': 'Item Description',
  'Vendor Name': 'Vendor Name',
  'Quantity': 'Quantity',
  'heading': 'Only those Issue/Receipt Transactions are shown which are performed in Digital Ledgers maintained in UDM',
  'heading1': 'Please Click here to see Issue/Receipt Transactions ',
  'dtlsissue':'Details of Issues',
  'RcptDetails': 'Receipt Details',
  'issuedtls': 'Issue Details',
  'ttlissue': 'Total Issues',
  'blc': 'Balance',
  'viewissuedetails': 'Issue Details',
  'dtsissue':'Details of Issues',
  'unitrate':'Unit Rate',
  'vocherno':'Voucher No.',
  'actdate':'Accountal Date',
  'qty' : 'Qty',
  'makebrand':'Make/Brand',
  'prdtslno':'Product Sl.No.',
  'warrantyupto':'Warranty upto',
  'issuenotedate':'Issue Note No & Date',
  'iisueqty':'Issued Qty',
  'blcqty':'Balance Qty',
  'tqdisp':'Total Qty. Dispatched  ',
  'tqr':'Total Qty. Received  ',
  'tqa':'Total Qty. Accepted  ',
  'tqrj':'Total Qty. Rejected  ',
  'twr':'Total Warranty Rejection ',
  'reinspectioninit':'Initial Rejected Qty. Accepted in Re-Inspection ',
  'reinspectionwarr':'Warranty Rejected Qty. Accepted in Re-Inspection  ',
  'Consignee Code1':'',
  'chDate':'',


  //====history sheet======
  'sacdetails' : 'STOCK, AAC AND CONSUMPTION DETAILS',
  'depot':'DEPOT',
  'wd':'WD',
  'cat':'CAT',
  'mdp':'MDP',
  'consales':'CONSUMPTION / SALES',
  'aac':'AAC',
  'ncp' : 'NCP',
  'stockmonth':'STOCK(MTHS)',
  'spare': 'SPARE STOCK',
  'lidt':'LI DT',
  'lrdt':'LR DT',
  'brate':'B.RATE',
  'unit' : 'UNIT',
  'year' : "Year",
  '1819':'Year(18-19)',
  '1920':'Year(19-20)',
  '2021':'Year(20-21)',
  '2122':'Year(21-22)',
  '2223':'Year(22-23)',

  'intentnumpur' : 'Indent No./Pur.Agency',

  'pw' : 'Please wait...',
  'refresh' : 'Refresh',

  'totconhed' : 'Total(Consumption)',

  // --- view details show ---

  'viewconsumption' : 'Click to view details of Stock and Consumption Details',
  'viewuncovered' : 'Click to view details of Un-covered Due Details',
  'viewintent' : 'Click to view details of Indent Details',
  'viewrlyboard' : 'Click to view details of Rly Board Indent Coverage Details',
  'viewcovereddue' : 'Click to view details of Covered Due Details',
  'viewmaterialunderaccountal' : 'Click to view details of Material Under Accountal',
  'viewmaterialrejected' : 'Click to view details of Material Rejected',
  'vieworderplace' : 'Click to view details of Orders Placed During last 5 Years',
  'viewoverstock' : 'Click to view details of Over Stock/Surplus/Inactive in Other Railway',

  'consumptionsnackertitle' : 'Do you want to see the Total Consumption Details?',
  'snackerview' : 'View',

  'savedpdf' : 'Download & save receipt',
  'stdwnd' : 'Downloading started...',

  // --- Non-Stck Demands ---
  'nonstocktitle' : 'NS Demands',
  'dashboard' : 'Dashboard',
  'fwdfnd' : 'Forwarded/Finalized by me',
  'awaitingaction' : 'Awaiting My Action',
  'casetracker' : 'Case Tracker',
  'status' : 'Status',
  'demandno' : 'Demand No.',
  'indentor' : 'Indentor',
  'consignee' : 'Consignee',
  'dmddtfrom' : 'Demand Date From',
  'dmddtto' : 'Demand Date To',
  'itemdesc' : 'Item Description',
  'proceed' : 'Proceed',
  'reset' : 'reset',
  'dmdnodt' : 'Demand No. & Date',
  'itemdetails' : 'Item Details',
  'valuemav' : 'Value & Min. Approval Level',
  'crnwith' : 'Currently with',
  'action' : 'Action',
  'dfctd' : 'Demand/File/Case/Tender No./Description',
  'prorly' : 'Procuring Railway',
  'itemsr' : 'Item & S.No.',
  'stknon' : 'Stock/Non-Stock',
  'casefile' : 'Case/File No.',
  'tendercls' : 'Tender No. & Closing Date',
  'selectsts' : '---Select Status---',
  'selectdept' : '---Select Department---',
  'selectcons' : '---Select Consignee---',
  'selectsubcons' : '---Select Sub-Consignee---',
  'selectindentor' : '---Select Indentor---',
  'dmdvalue' : 'Demand Value (Rs.)',
  'purpose' : 'Purpose',
  'fundavlyear' : 'Fund Availability Year',
  'spni' : 'Safety/Passenger Necessity Item?',
  'wac' : 'Whether PAC Case?',
  'idr' : 'Indentor Demand Reference',
  'sen' : 'Sanctioned Estimate No.',
  'ed' : 'Estimate Date',
  'ein' : 'Estimate Item No.',
  'pt' : 'Procurement Type',
  'pu' : 'Purchase Unit',
  'itemdet' : 'Item Details',
  'vaa' : 'Vendor Approving Agency',
  'tq' : 'Total Qty.',
  'raters' : 'Rate (Rs.)',
  'valuers' : 'Value (Rs.)',
  'consignee' : 'Consignee',
  'qty' : 'Quantity',
  'state' : 'State',
  'reqat' : 'Required at',
  'inhandqty' : 'In-Hand Qty.',
  'drb' : 'Delivery Reqd. by',



  //--------Rejection/Warranty UI-------

  'rwtitle' : 'Rejection/Warranty',
  'rwwarantycmptitle' : 'Warranty Complaint Data',
  'fwctitle' : 'My Forwarded Claims',
  'apdtitle' : 'My Approved/Dropped Claims',
  'wcp' : 'Warranty Claim from Period',
  'pt' : 'Period To',
  'fromdate' : 'Date: From',
  'todate' : 'Date: To',
  'status' : 'Status',
  'rwsearch' : 'Search',
  'rwsearchhint' : 'Please Enter Warranty Claim No./DMTR No/Item Code/Item Description',
  'rwexit' : 'Exit',
  'rwsource' : 'Source',
  'rwcmpform' : 'Complaint From',
  'rwcmpref' : 'Complaint Ref',
  'rwpono' : 'PO No.',
  'rwvendorname' : 'Vendor Name',
  'rwposr' : 'PO Sr',
  'rwstkns' : 'Stock/NS',
  'rwplno' : 'PL No.',
  'rwitemdesc' : 'Item Description',
  'rwqty' : 'Qty',
  'rwinsagency' : 'Inspecting Agency',
  'rwapproagency' : 'Approving Agency',

  'wcref' : 'Warranty Claim No. & Rejection/Supply Ref',
  'pocontract' : 'PO-Contract No. & Date/Challan No. & Date',
  'rejqty' : 'Rejected Qty',
  'rwrate' : 'Rate(Rs.)',
  'rwvalue' : 'Value(Rs.)',
  'rwftodate' : 'Forwarded To/Date',
  'badresp' : 'Bad Response from server',
  'refnow' : 'Refresh Now',
  'tryagain' : 'Try Again',
  'monthwarning' : 'Invalid start & end date to show records',
  'rwalert' : 'Alert!',
  'rwmonthwrtitle' : "Sorry, You can't see data above six month from start date to end date.",

  //=================gemorder details=======================
  'gemorderdtl' : 'GeM Order Detais',
  'gemorderno' : 'GeM Order No. :',
  'search1' : 'Search',
  'gemhint' : 'GEMC-511687702',
  'oredrid' : 'Please Emter OrderID',

  'buyerdetails' : 'Buyer Details',
  'org' : 'Organization',
  'buyername' : 'Buyer Name',
  'buyeradrs' : 'Buyer Address',
  'mobno' : 'Mobile No.',

  'gemorderdetails' : 'GeM Order Details' ,
  'ordernodate' : 'Order No. & Order Date' ,
  'venname' : 'Vendor Name' ,
  'venpangstn' : 'Vendor PAN & GSTN' ,
  'noofitem' : 'No. of Items' ,
  'orderamt' : 'Order Amount (Rs.)' ,
  'aucode' : 'AU Code' ,
  'accountingunit' : 'Accounting Unit' ,
  'paymentmode' : 'Payment mode' ,

  'consdetails' : 'Consignee Details' ,
  'sno' : 'S. No.' ,
  'consname' : 'Consignee Name' ,
  'consadd' : 'Consignee Address' ,
  'mobno' : 'Mobile No.' ,
  'itemdtls' : 'Item Details' ,
  'sino' : 'Sl. No.' ,
  'des' : 'Description' ,
  'qty' : 'Qty.' ,

  'covpodtls' : 'Covering PO Details' ,
  'pono' : 'PO No.' ,
  'podate' : 'PO Date' ,
  'venname' : 'Vendor Name' ,
  'povalue' : 'PO Value' ,
  'payauth' : 'Paying Authority' ,

  'matrecaccdtls' : 'Material / Accountal Details' ,
  'cons' : 'Consignee' ,
  'dmtrrecnodate' : 'DMTR/DRR No. &',
  'dmtrdate' : 'Receipt Date',
  'doctype1' : 'Document Type' ,
  'ronodate' : 'RO No. & Date' ,
  'dispqty' : 'Dispatched Qty.' ,
  'receqty' : 'Received Qty.' ,
  'accptqty' : 'Accepted Qty.' ,
  'rejecqty' : 'Rejected Qty.' ,

  'billdtlsgemportal' : 'CRAC & GeM Bill Details' ,
  'consname' : 'Consignee Name' ,
  'invoicenodate' : 'Invoice No. & Date' ,
  'cracdtls' : 'CRAC Details' ,
  'billnodate' : 'Bill No. & Date' ,
  'billamts' : 'Bill Amount (Rs.)' ,
  'co6numdate' : 'CO6 No. & Date' ,
  'co7numdate' : 'CO7 No. & Date' ,
  'passamts' : 'Passed Amount (Rs.)' ,
  'dedamts' : 'Deducted Amount (Rs.)' ,
  'paydate' : 'Payment Date' ,
  'redate' : 'Return Date' ,
  'rereasons' : 'Return Reason',

  'dedamtdtls' : 'Deducted Amount Details in IPAS' ,
  'sno' : 'S.No.' ,
  'dtlsded' : 'Details of Deduction' ,
  'amtsr' : 'Amount (Rs.)' ,
  'blank' : '',
  'dedhead' : 'Please Click here to see CRAC & GeM Bill Details generated on GeM Portal',

  //------ NS Demand Summary -------
  'nsdemandtitle' : 'NS Demand Summary',
  'nsdatefrom' : 'NS Demand Date: From',
  'nsdateto' : 'NS Demand Date: To',
  'nsdrailway' : 'Railway',
  'nsdunittype' : 'Unit Type',
  'nsdunitname' : 'Unit Name',
  'nsddepartment' : 'Select Department',
  'nsdconsignee' : 'Indenting Consignee Code',
  'nsdindentor' : 'Indentor Name',
  'nsdsubmit' : 'Submit',

  'nsdrly' : 'Rly',
  'nsdunittype' : 'Unit Type',
  'nsdunitname' : 'Unit Name',
  'nsddept' : 'Department',
  'nsdcon' : 'Indenting Consignee',
  'nsdindentor' : "Indentor's Name",
  'total' : 'Total',
  'drf' : 'In Draft Stage',
  'ufc' :  'Under Finance Concurrence',
  'ufv' : 'Under Finance veting',
  'underprc' : 'Under Process',
  'apfwd' : 'Approved & Forwarded to Purchase',
  'rtpurchase' : 'Returned by Purchase Unit',
  'dropped' : 'Dropped',

  'dmdnumdate' : 'Demand No. & Date',
  'indetortitle' : 'Indentor',
  'itemdetails' : 'Item Details',
  'valueminappr' : 'Value & Min. Approval Level',
  'purunit' : 'Purchase Unit',
  'currentlywith' : 'Currently With',
  'status' : 'Status',
  'viemdmd' : 'View Demand',
  'sdnf' : 'Sorry, document not found',
  'pdls' : 'PDF document loaded successfully!',
  'docend' : 'Document End!',

  //warranty Complaint
  'warrantycomsum' : 'Warranty Complaint Summary',
  'cfrom': 'Complaints From:',
  'cto': 'Complaints To:',
  'csource': 'Complaint Source',
  'ccodegencom': 'Consignee Code Generating Complaints',
  'rlc': 'Railway to Lodge Claim',
  'concodelc': 'Consignee Code to Lodge Claim',
  'submit': 'Submit',
  'reset': 'Reset',
  'compsource': 'Complaint Source',
  'rlgencomplaint': 'Railway Generating Complaint',
  'rlyvendor': 'Railway To Lodge Warranty Claim On Vendor',
  'complaint': 'Complaint',
  'total': 'Total',
  'lodgevendor': 'Where Claim Lodged On Vendor',
  'initiatedvendor': 'Where Claim Initiated On Vendor',
  'retmaintapp': 'Returned To Maint.App.',
  'apvvendor': 'Where Advice Note To Store Depot Approved For Lodging Claim On Vendor ',
  'initiatedvendor': 'Where Advice Note To Store Depot Initiated For Lodging Claim On Vendor',
  'returnedvendor':'Where Advice Note Returned by Store Depot Without Lodging Claim on Vendor',
  'actioninitiated':'Where Action yet to be Initiated',
  'warrantycom':'Complaint Summary',
  'source':'Source',
  'complaintrailway':'Complaint Railway',
  'complaintconsginee':'Complaint Consignee',
  'railwaylodgeclaim':'Railway to Lodge Claim',
  'consgineelodgeclaim':'Consginee To Lodge Claim',
  'rejection':'Rejection ref',
  'plno':'PL NO.',
  'item':'Item',
  'qty':'Qty',
  'vendor':'Vendor',
  'status':'Status',
  'claimno':'Claim No',
  'claimdate':'Claim Date',
  'claimamount':'Claim Amount',

  // ------ Stocking Proposal Summary Screen ------
  'stkprptitle' : 'Stocking Proposal Summary',
  'stkprfromdate' : 'Stocking Proposal Date: From',
  'stkprtodate' : 'Stocking Proposal Date: To',
  'stksummaryrly' : 'Railway',
  'stksummarydept' : 'Department',
  'unitinitprpsl' : 'Unit Initiating Proposal',
  'unifyingrly' : 'Unifying Railway',
  'storedepot' : 'Stores Depot',
  'totprpinit' : 'Total Proposal Initiated',
  'prpindrfdatege' : 'Proposals in Draft Stage',
  'prpother' : 'Proposals with Deptts. other than Stores',
  'prpstrdepot' : 'Proposals with Stores Depot',
  'prppcm' : 'Proposals with PCMM office',
  'prpunifrly' : 'Proposals with Unifying Rly',
  'prprejected' : 'Proposals Rejected by Unifying Rly',
  'prpreturned' : 'Proposals Returned to initiator',
  'stcprpdrop' : 'Stocking Proposal Dropped',
  'stkprpapp' : 'Stocking Proposal Approved',
  'selectinitprp' : '--Select Initiating Proposal--',
  'selunifyingrly' : '--Select Unifying Railway--',
  'selectdept' : '--Select Department--',
  'selstoresdepot' : '--Select Stores Depot--',
  'stkappnumdate' : 'Stocking Application No. & Date',
  'plsubgroup' : 'PL Group/Sub-Group',
  'itemdesc' : 'Description of Item',
  'stkinitiatorname' : "Initiator's Dtails",
  'currentwith' : 'Currently With',
  'status' : 'Status',


  //---------CRN Summary----------------
  'crnsum':'CRN Summary',
  'rcptdatefrom':'Receipt Date: From',
  'rcptdateto':'Receipt Date: To',
  'rly':'Railway',
  'unittype':'Unit Type',
  'unitname':'Unit Name',
  'slctdepart':'Select Department',
  'slctuserdepo':'Select User Depot',
  'subcons':'Sub-Consignee',
  'r1':'Rly',
  'depart':'Department',
  'cons&subcons':'Consignee & Sub-Consignee',
  'openbalence':'Opening Balance(Consignments where Digitally-Signed CRN pending)',
  'newconsrecvd':'New Consignments Recevied',
  'conswheredigisign':'Consignments where Digitally-Signed CRNs issued',
  'closebalnc':'Closing Balance(Consignments where Digitally-Signed CRN pending)',
  'breakuoppen':'Break-up of Pending Digitally-Signed CRNs',
  '7days':'<7 Days',
  '7to15':'7 to 15 Days',
  '15to30':'15 to 30 Days',
  '30d':'>30 Days',
  'ponumdate':'PO No. & Date',
  'venname':'Vendor Name',
  'poser':'PO Sr.',
  'des1':'Description',
  'datereceipt':'Date of Receipt',
  'dmtrnum':'DMTR No. & Date',
  'qtyrecvd':'Qty. Received',
  'qtyacpt':'Qty. Accepted',
  'val1':'Value(Rs.)',
  'curstatus':'Current Status',


  // ---- Warranty Rejection Register -----
  'wrrtitle':'Warranty Rejection Register',
  'wcfp' : 'Warranty Claim from Period',
  'pt' : 'Period To',
  'sv' : 'Search Vendor',
  'wrrsearch' : 'Search',
  'svhint' : 'Please type Vendor Name',
  'shint' : 'Please Enter Warranty Claim No/DMTR No/Item Code/Item Description',
  'wrrall' : "All",
  'wrrpenr' : 'Pending Recovery',
  'wrrnilrcr' : 'Nil Recovery',
  'wrrretvendor' : 'Material to be Returned to Vendor ( Nil Recovery)',
  'wrrsubmit' : 'Search',
  'wrrexit' : 'Exit',

  'wcrrd' : 'Warranty Claim & Receipt/Rejection Details',
  'vendor' : 'vendor Name',
  'wrrponumdate' : 'PO-Contract No. & Date/Challan No. & Date',
  'itemdesc' : 'Item Description',
  'qrcwwb' : 'Quantity Rejected/Claim Withdrawn/Bal.Rej.Avail',
  'qrarrr' : 'Quantity Re-Insp./Accept.(Re-Insp.)/Returned/Replaced',
  'orwarabr' : 'Orig.Recovery/Recov.Amt./Bal.Recovery',
  'vorqbrqau' : 'Value Orig.Rej.Qty./Bal.Rej.Qty./Acct. Unit',
  'rrrml' : 'Rejection Reason/Rejected Material Location',
  'action' : 'Action',

  'twcao' : 'Total Warranty Claim Amount (Original)',
  'twcac' : 'Total Warranty Claim Amount (Current)',

  'rejadvreg' : 'Rejection Advice Register',
  'warrejreg' : 'Warranty Rejection Register',
  'txntype' : 'Transaction Type',

  'swcf' : 'Summary of Warranty Claim From:',
  'wrrto' : 'To:',

  'wra' : 'WARRANTY REJECTION ADVICE',
  'ratitle' : 'REJECTION ADVICE',
  'wran' : 'Warranty Rejection Advice No.',
  'ran' : 'Rejection Advice No.',
  'pocn' : 'PO/Contract No.',
  'pocd' : 'PO/Contract Date',
  'isrpoc' : 'Item Sl.No. In PO/Contract',
  'crr' : 'Consignee Reporting Rejection :',
  'sdsc' : 'Sub-Depot/Sub-Consignee:',
  'cn' : 'Complaint No.:',
  'rarn' : 'Rejection Advice Regn No.:',
  'cd' : 'Complaint Date:',
  'nas' : 'Name & Address of Supplier:',
  'cnum' : 'Challan-No.:',
  'cnumd' : 'Challan Date:',
  'icnum' : 'IC-No.:',
  'icd' : 'IC Date:',
  'islnum' : 'ISL-No.:',
  'drrn' : 'DRR-No.:',
  'drrd' : 'DRR Date:',
  'isld' : 'ISL Date:',
  'dds' : 'Description & Drg./Spec.',
  'pnic' : 'PL.No./Item Code:',
  'iby' : 'Inspection by:',
  'icn' : 'IC No',
  'vaa' : 'Vendor Approving Agency:',
  'qr' : 'Quantity Rejected:',
  'qrw' : 'Quantity Rejected (in words):',
  'ror' : 'Reason of Rejection:',
  'ru' : 'Rate/Unit:',
  'ha' : 'Head/Allocation:',
  'camt' : 'Claim Amount: ',
  'ra' : 'Recovery-Advice:',
  'note' : 'Note:',
  'rfia' : 'Remarks for Inspecting Agency:',
  'cpa' : 'Concerned Paying Authority:',
  'sdo' : 'SHOP/DEPOT OFFICIAL',
  'co' : 'CONTROLLING OFFICER',

  'wr' : 'Withdrawn Reference',
  'qw' : 'Qty. Withdrawn',
  'duc' : 'Details of User Depot/Consignee',
  'dad' : 'Digital Authority Document',

  'rivnum' : 'Re-Inspection Voucher No.',
  'dpri' : 'Date for putting up for Re-Inspection',
  'dri' : 'Qty. put up for Re-Inspection',
  'qari' : 'Qty. Accepted after Re-Inspection',
  'dari' : 'Date of Accountal after Re-Inspection',
  'dudc' : 'Details of User Depot/Consignee',
  'dcsd' : 'Digital CRN Status/Doc.',
  'mb' : 'Make/Brand:',
  'bpsn' : 'Batch/Product Sl. No.',
  'wp' : 'Warranty Period:',
  'adpymt' : 'Advance-Payment:',

   'ddars' : 'DMTR No. & Date of Accountal of Replacement Supplies',
   'qtyr' : 'Qty.Replaced',
   'scnd' : "Supplier's Challan No. & Date",
   'drrs' : 'Date of Receipt of Replacement Supplies',

    'recdate' : 'Recovery Date',
    'amtrec' : "Amount Recovered (Rs.)",
    'co6num' : 'CO6 Number',
    'co6date' : 'CO6 Date',
    'ponum' : 'PO No',

    'rwhd' : 'Recovery/ With-holding Date',
    'arwh' : 'Amount Recovered/ With-held (Rs.)',
    'rwhdet' : 'Recovery/ With-holding Details',
    'derwhd' : 'Date of entering Recovery/ With-holding Details',
    'uac' : 'User/ Application concerned',

    'frbd' : "Firm's Refund Bill Details",
    'rr' : 'Refunding Railway',
    'amtrr' : 'Amount Refunded (Rs.)',
    'refd' : 'Refund Details',

  'rrvn' : 'Recovery Refund Voucher No.',
  'rrvd' : 'Recovery Refund Voucher Date',
  'rrar' : 'Recovery Refund Amount (Rs.)',
  'rrvdoc' : 'Recovery refund Voucher doc',

  'innd' : 'Issue Note No. & Date',
  'qtyret' : 'Qty.Returned',
  'srnd' : "Supplier's Reference No. & Date",
  'gpd' : 'Gate Pass Details',
  'issuenote' : 'Issue Note',
  'rmndnumdos' : 'Rejection Memo No. & Date/DMTR No. & Date of Supply',
  'itemdescrs' : 'Item Description/Recovery Status',
  'qtysplyaccrbrq' : 'Qty. Supplied/Accepted/Rejected/Bal.Rej.Qty.',
  'triqtrq' : 'Total Re-Insp. Qty./Total Returned Qty.',
  'rorraba' : 'Rate/Original Recovery/Recov. Amt./Balance Recovery',

  'tora' : 'Total Original Recovery Amount',
  'tcra' : 'Total Current Recovery Amount',
  'tvoorq' : 'Total Value of Original Rejected Qty',
  'tvobrq' : 'Total Value of Balance Rejected Qty',

  'condepot' : 'Consignee Depot',

  'viewwrntyclaim' : 'View Warranty Claim',

  //---------CRC Summary----------------
  'crcsum':'CRC Summary',
  'grandtotal' : 'Grand Total',
  'openbalencecrc':'Opening Balance(Consignments where Digitally-Signed CRC pending)',
  'conswheredigisigncrc':'Consignments where Digitally-Signed CRCs issued',
  'closebalnccrc':'Closing Balance(Consignments where Digitally-Signed CRC pending)',
  'breakuoppencrc':'Break-up of Pending Digitally-Signed CRCs',
  'depttitle' : 'Deptt.',
  'userdepotconsignee' : 'User Depot/Consignee',
  'subconsignee' : 'Sub-Consignee',
  'desccrc' : 'Summary of Digitally signed CRCs for Non-Stock Items supplied by vendors from',
  'posason' : 'Position as on',
  'crcto' : 'to',
  'totvaluers' : 'Grand Total',
  'listingtype' : 'Type of Lisiting:',

  //---------To End User Screen----------------
  'endusertitle' : 'To End User',
  'ledgerno' : 'Ledger No.',
  'ledgername' : 'Ledger Name',
  'ledgerfolionum' : 'Ledger folio number',
  'ledgerfolioname' : 'Ledger folio name',
  'ledgerfolioitem' : 'Ledger folio item',
  'endusersearch' : 'Search',
  'selectledgernum' : '--Select Ledger Number--',
  'sln' : 'Select ledger number',
  'slfn' : 'select ledger folio number',
  'slfi' : 'Select ledger folio item',
  'selectledgerfolionum' : '--Select Ledger Folio Number--',
  'selectledgerfolioitem' : '--Select Ledger Folio Item--',
  'searchbtn' : 'Search',
  'ledger' : 'Ledger',
  'ledgerfolio' : 'Ledger Folio',
  'itemcodeplno' : 'Item Code/PL No',
  'itemDesc' : 'Item Description',
  'stkqty' : 'Stock Qty',
  'stkv' : 'Stock Value',
  'action' : 'Action',
  'allocation' : 'Allocation',
  'weorkorderno' : 'Work Order No.',
  'enduserunit' : 'Unit',
  'euvalue' : 'Value',
  'qbi' : 'Qty being Issued(in Nos.)',
  'iwi' : 'IRPSM Work ID',
  'iwd' : 'IRPSM Work Detail',
  'recd' : "Receiver's Details",
  'issuetype' : 'Issue Type',
  'adi' : 'Actual Date of Issue',
  'at' : 'Asset type',
  'purpu' : 'Purpose/Usage',
  'issuebtn' : 'Issue',
  'wred' : 'Warranty/Expiry Date',
  'qdbi' : 'Qty of DMTR to be Issued',
  'dbq' : 'DMTR Balance Qty',
  'loc' : 'Location',
  'rf' : 'Received From',
  'dmtrD' : 'DMTR Details',
  'asd' : 'Available Stock Details',
  'puru' : 'Purpose/Usage',
  'asir' : 'All selection input is required',
  'lficid' : 'Ledger folio name/Item Code/Item Description',
  'sfi' : 'Select folio item',
  'pedmnum' : 'Please enter demand no.',
  'peallocation' : 'Please enter allocation',
  'peworkordernum' : 'Please enter work order no.',
  'peq' : 'Please enter quantity',
  'pewid' : 'Please enter work ID',
  'pewd' : 'Please enter work detail',
  'perd' : 'Please enter receiver details',
  'pepu' : 'Please enter purpose/usage',

  //------ Settings Screen------
  "settingritle" : "Settings",
  'profile' : 'Profile',
  'changepin' : 'Change Pin',
  'changelogin' : 'Change Login',
  'changelan' : 'Change Language',
  'confirmtitle' : 'Confirmation!!',
  'cdesc' : 'Do you want to logout from application?',
  'wdyes' : 'Yes',
  'wdno' : 'No',
  'selela' : 'Select Language',
  'endok' : 'Ok',

  // -----------Warranty CRN Summary Screen-----------------
  'erstitle' : 'Warranty CRN Summary',
  'wcfd' : 'Warranty Claim: From Date',
  'wct' : 'Warranty Claim: To',
  'wcsrcptdatefrom':'Receipt Date: From',
  'wrcrcptdateto':'Receipt Date: To',
  'wrcrly':'Railway',
  'wrcunittype':'Unit Type',
  'wrcunitname':'Unit Name',
  'wrcslctdepart':'Select Department',
  'wrcslctuserdepo':'Select User Depot',
  'wrcsubcons':'Sub-Consignee',
  'wrcvendor':'Vendor',

 //------------------------ Helpdesk Screen--------------------------
 'helpdesktitle' : 'Helpdesk',
 'qss' : 'For Any Query/Suggestions/Support',
 'contactus' : 'Contact Us',
 'phone' : 'Phone',
 'email' : 'Email',
 'enow' : 'Email Now',
 'cnow' : 'Call Now'
};