Map<String, String> hindiText = {

//---- No Internet Screen ----
  "errortitle" :  "कोई इंटरनेट कनेक्शन नहीं",
  "errordesc" :  "कृपया इंटरनेट से कनेक्ट करें और पुनः प्रयास करें",
  "tryagainbtn" : "पुनः प्रयास करें",

  //Login Screen
  'userId': 'यूजर आईडी',
  'emailId': 'ईमेल आईडी',
  'enterPin': 'पिन दर्ज करें',
  'saveCred': '05 दिनों के लिए  लॉग-इन विवरण सेव करे',
  'login': 'लॉग-इन करें',
  'enableAccessLabel1': 'UDM ऐप के लिए ',
  'enableAccessLabel2': 'लॉग-इन  एक्सेस ',
  'enableAccessLabel3': ' कैसे करें?',
  'resetPinInstructionsLabel1': 'पिन कैसे ',
  'resetPinInstructionsLabel2': 'री-सेट  करें',
  'loginScreenInstructions1': 'www.ireps.gov.in पर लॉग इन करें',
  'loginScreenInstructions2': 'दाईं ओर ऊपरी कोने पर स्विच आइकन पर क्लिक करें',
  'enableAccessInstructionsTitle': 'UDM ऐप पर लॉग-इन  करने के लिए',
  'enableAccessInstructionsText':
  '’Enable Mobile Access’ पर क्लिक करें और प्रक्रिया को पूरा करें',
  'resetPinInstructionsTitle': 'UDM ऐप पिन री-सेट  करने के लिए',
  'resetPinInstructionsText':
  '‘Reset APP PIN’ पर क्लिक करें और प्रक्रिया को पूरा करें',
  'validEmail' : 'कृपया वैध ईमेल-आईडी दर्ज करें',
  //Home Screen
  'udmFull': 'यूजर डिपो मॉड्यूल',
  'udmtitle' : 'यूजर डिपो मॉड्यूल(यूडीएम)',
  'irepslabel' : 'आईआरईपीएस',
  'udmlabel' : 'यूडीएम',
  'home' : 'होम',
  'profile' : 'प्रोफ़ाइल',
  'settings' : 'सेटिंग',
  //Change PIN
  'changePin': 'पिन बदलें',
  'confirmPin': 'नए पिन की पुष्टि करें',
  'enterOldPin': 'पुराना पिन दर्ज करें',
  'enterNewPin': 'नया पिन दर्ज करें',
  "confirm":'पुष्टि करें',
  'cancel':'रद्द करें',
  'logout' : 'लॉगआउट करें',
  'logOut':'इस डिवाइस से लॉगआउट करें?',
  'changeLogin':'लॉगिन बदलें',
  'checkconnection' : 'कृपया अपने इंटरनेट कनेक्शन की जाँच करें!!',

  'rateUs': 'हमें रेट करें',
  'version': 'संस्करण',
  //Profile
  'profile': 'प्रोफाइल',
  'userDetails': 'उपयोगकर्ता की जानकारी',
  'orgDetails': 'संगठन का विवरण',
  'lastLogin': 'अंतिम लॉग-इन  समय',
  //Search Item
  'searchItem': 'आइटम खोजें',
  'reset': 'री-सेट ',
  'submit': 'सबमिट',
  'pinLengthError': 'कृपया 6-12 अंकों का पिन दर्ज करें',
  'railway': 'रेलवे',
  'unitType': 'यूनिट टाइप',
  'unitName': 'यूनिट का नाम',
  'departmentName': 'विभाग का नाम',
  'userDepot': 'यूजर डिपो',
  'getDetails': 'विवरण प्राप्त करें',
  'plNo': 'पीएल नंबर',
  'description': 'विवरण',
  'plNoDisplayText': 'PL / विवरण के न्यूनतम 3 अक्षर दर्ज करें',
  'plNoErrorText': '३ से अधिक होनी चाहिए अक्षर दर्ज करें',
  //Item List
  'department': 'विभाग का नाम',
  'itemList': 'सामान की सूची',
  'totalCount': 'कुल संख्या',
  'pl/itemCode': 'पीoएलo/आइटम कोड',
  'ledgerName': 'खाता का नाम',
  'ledgerNo': 'खाता संख्या',
  'ledgerFolioNo': 'खाता पन्ना संख्या',
  'itemCategory': 'आइटम की श्रेणी',
  'itemDescription': 'आइटम का विवरण',
  'consigneeCode': 'परेषिती का कोड',
  'consigneeDepot': 'परेषिती डिपो',
  'lastReceipt': 'पिछली रसीद',
  'issueDate': 'जारी करने की तिथि',
  'stock': 'भण्डार',
  'averageRateRs': 'औसत दर (₹)',
  'valueRs': 'मूल्य (₹)',
  'aac': 'एoएoसीo',
  'briefDescription': 'संक्षिप्त विवरण',
  'summary': 'सारांश',
  'recordFound': 'रिकॉर्ड मिला',
  'more': 'अधिक',
  'less': 'कम',
  'totalQuantity': 'कुल मात्रा',
  'quantity': 'मात्रा',
  'unit': 'इकाई',
  'totalVal': 'कुल मूल्य (₹)',
  'rate': 'भाव',
  //User Depot Details
  'userDepotDetails': 'उपयोगकर्ता डिपो का विवरण',
  'saveContact': 'संपर्क सहेजें',
  'overallDetailsHeading': 'प्रभारी का विवरण',

  //Stock Availability
  'stockAvailability': 'स्टॉक उपलब्धता',
  'userSubDepot': 'उपयोगकर्ता उप डिपो',
  'selectReportCriteria': 'रिपोर्ट मानदंड चुनें',
  'selectStockAvailability': 'स्टॉक उपलब्धता का चयन करें',
  'aacBasis': 'एoएoसीo का  आधार',
  'thresholdLimitBasis': 'सीमा का आधार',
  'greaterThan': 'से अधिक',
  'lessThan': 'से कम',
  'monthsBasedOnAAC': 'एoएoसीo पर आधारित महीने',
  'itemType': 'आइटम का प्रकार',
  'itemUsage': 'आइटम का उपयोग',
  'stockNonStock': 'स्टॉक/गैर-स्टॉक',
  'times': 'समय',
  'thresholdLimit': 'सीमा - रेखा',

  //Stores Depot Stock
  'storesDepotStockList': 'स्टोर डिपो स्टॉक सूची',
  'storesDepotStock': 'भण्डार डिपो स्टॉक',
  'storesDepot': 'भंडार डिपो',
  'stockSummary': 'स्टॉक का संक्षिप्त विवरण',
  'ward': 'वार्ड',
  'nonMovingItems': 'नॉन-मूविंग आइटम',
  'rateRs': 'भाव (₹)',
  'valueWiseStock': 'वैल्यू अनुसार स्टॉक',
  'stockQty/Unit': 'स्टॉक मात्रा / यूनिट',
  'highValueItems': 'उच्च वैल्यू आइटम',
  'pl/min3Desc': 'विवरण का पीoएलo / न्यूनतम 3 वर्ण दर्ज करें',

  'consAnalysis': 'खपत का विश्लेषण',

  'consSummary': 'खपत का संक्षिप्त विवरण',

  'transaction': 'लेनदेन',
  'poSearch': 'पीoओo ढूँढें',

  //Search PO
  'PONo': 'पीoओo संख्या',
  'enterPONo': 'पीoओo संख्या दर्ज करें',
  'vendorName': 'विक्रेता का नाम',
  'enterVendorName': 'विक्रेता का नाम दर्ज करें',
  'POPlacingAuthority': 'पीoओo प्लेसमेंट अथॉरिटी',
  'coverageStatus': 'कवरेज स्थिति',
  'PODateFrom': 'पीoओo तिथि: से',
  'PODateTo': 'पीoओo तिथि: तक',
  'purchaseSection': 'खरीद अनुभाग',
  'tenderType': 'टेंडर प्रकार',
  'inspectionAgency': 'जांच एजेंसी',
  'industryType': 'उद्योग प्रकार',
  'POType': 'पीoओo प्रकार',
  'POValue': 'पीoओo मूल्य',
  'enterPODateFrom': 'शुरुआत की पीoओo तिथि दर्ज करें',
  'enterPODateTo': 'अंतिम पीoओo तिथि दर्ज करें',
  'pleaseSelectDatesTo': 'कृपया 3 महीने के भीतर खोज अवधि रखने के लिए तिथियों का चयन करें',
  'itemDescriptionWarning': 'आइटम विवरण तीन वर्णों से बड़ा होना चाहिए',
  'descpowarning' : 'कृपया आइटम विवरण के 3 अक्षर या पीओ नंबर दर्ज करें।',
  'POValueFrom': 'शुरुआत का पीoओo मूल्य(₹)',
  'POValueTo': 'अंतिम पीoओo मूल्य(₹)',
  'POValueFromHint': 'शुरुआत का पीoओo मूल्य(₹) दर्ज करें',
  'POValueToHint': 'अंतिम पीoओo मूल्य(₹) दर्ज करें',
  'noDataFound': 'कोई डेटा नहीं मिला',
  'searchWithSameInput': '12 महीने की अवधि के लिए समान इनपुट के साथ खोजें?',
  'yes': 'हां',
  'no': 'नहीं',
  'PONoAndDate': 'पीoओo संख्या और तिथि',
  'code': 'कोड',
  'POSrNo': 'पीoओo सीरियल नंबर',
  'PLNo': 'पीoएलo संख्या',
  'itemQuantity': 'आइटम की मात्रा',
  'deliveryDate': 'डिलीवरी की तिथि',
  'itemUnitRate': 'आइटम यूनिट दर (₹)',
  'itemValue': 'आइटम मूल्य',
  'quantityReceived': 'प्राप्त मात्रा',
  'paidValue': 'भुगतान मूल्य (₹)',

  //PO search action
  'viewContactDetails': 'संपर्क विवरण देखें',
  'vendorCode': 'विक्रेता कोड',
  'nonStock':'गैर-स्टॉक',
  'stockingStoreDepot':'स्टॉक भंडार डिपो',


  //Summary of Stock
  'summaryOfStock': 'स्टॉक का सारांश',
  'userDepotStockSummary': 'यूजर डिपो स्टॉक सारांश',

  //Non-Moving Items
  'months': 'महीने का',
  'itemNotIssuedSince1Month': 'आइटम पिछले 1 महीने से जारी नहीं किया गया',
  'usage': 'उपयोग',
  'type': 'टाइप',
  'category': 'श्रेणी',

  //Value-Wise Stock
  'valueInRsDefinedByUser': 'उपयोगकर्ता द्वारा परिभाषित मूल्य (₹)',

  //High Value Items
  'top': 'शीर्ष',
  'highValueItemsAsPerStockValue':
  'उच्च मूल्य वाले आइटम (स्टॉक मूल्य के अनुसार)',

  //Consumption Analysis
  'currentPeriod': 'वर्तमान अवधि',
  'previousPeriod': 'पिछली अवधि',
  'from': 'से',
  'to': 'तक',
  'percentageChange': 'प्रतिशत परिवर्तन',
  'by': 'से',
  'increase': 'जमा (+)',
  'decrease': 'घटा (-)',
  'consAnalysis':'खपत का विश्लेषण',
  'avgMonthlyConsCurrentP':'वर्तमान अवधि में औसत मासिक खपत',
  'avgMonthlyConsPreP':'पिछली अवधि में औसत मासिक खपत',
  // Consumption Summary
  'chooseSummaryType': 'सारांश प्रकार चुनें',
  'topNHighConsumptionValueItems': "शीर्ष (N) उच्च खपत मूल्य आइटम",
  'itemsHavingConsumptionValueAboveSpecifiedLimit':
  'निर्दिष्ट सीमा से अधिक खपत मूल्य वाले आइटम',
  'consumptionComparisonWithAAC': 'एoएoसीo के साथ खपत की तुलना',
  'specifyNNoOfTop':
  "शीर्ष उच्च मूल्य वाली वस्तुओं की 'N' संख्या निर्दिष्ट करें",
  'specifyLimitOfConVal': 'खपत मूल्य की सीमा निर्दिष्ट करें (₹)',
  'percentageGreater': 'प्रतिशत से अधिक (>)',
  'percentageLess': 'प्रतिशत से कम (<=)',
  'proportionateQtyAsPerAAC': 'एएसी के अनुसार आनुपातिक मात्रा',
  'consumptionSummary': 'खपत सारांश',
  'consumptionVal': 'खपत मूल्य (₹)',
  'consumptionQty': 'खपत मात्रा',

  //Transaction Search
  'searchPLItemFolioDesc': 'पीएल/आइटम/फोलियो/विवरण ',
  'searchPLItemFolioDescHint':
  'पीएल नंबर / आइटम कोड / फोलियो का नाम / विवरण खोजें',
  'ledgerFolioPlNo': 'लेज़र फोलियो पीएल नंबर',
  'folioNo': 'फोलियो नंबर',
  'fromDate': 'दिनांक से',
  'toDate': 'दिनांक तक',

  //Transaction Summary
  'transactionSummary': 'लेनदेन का सारांश',
  'details': 'विवरण',
  'date': 'दिनांक',
  'noDateOfReceipt': 'रसीद/जारी करने की \nसंख्या और तारीख',
  'myNameIs': 'मेरा नाम है ',
  'receiptQuantity': 'रसीद मात्रा',
  'issueQuantity': 'इश्यू मात्रा',
  'balanceQuantity': 'शेष मात्रा',
  'initials': 'आद्याक्षर',
  'remarks': 'राय',
  'receivedFromIssuedTo': 'से प्राप्त किया / के लिए जारी किए',
  'transactionDetailsFor': 'अवधि के लिए लेनदेन विवरण:',
  'folioName': 'फ़ोलियो का नाम',
  'nameOfArticleItem': 'लेख/वस्तु का नाम',
  'unitWeight': 'यूनिट वजन (किलो में)',
  'existingThresholdUnit': 'मौजूदा थ्रेसहोल्ड यूनिट',
  'ledger': 'खाता बही',
  'transactionUnit': 'ट्रांजेक्शन यूनिट',
  'recepitsDuringSelectedPeriod': 'चयनित अवधि के दौरान प्राप्तियां:',
  'issueDuringSelectedPeriod': 'चयनित अवधि के दौरान जारी की गई:',
  'balanceAtEndOfPeriod': 'चयनित अवधि के अंत में शेष राशि:',
  'currentClosingBalance': 'वर्तमान समापन शेष',
  'currentClosingBalanceValue': 'वर्तमान समापन शेष\nमूल्य (₹)',
  'averageRate': 'औसत दर (₹)',
  'itemDetails':'आइटम विवरण',
  'itemSummary':'आइटम सारांश',
  'consignee':'परेषिती',
  'subDepot':'उप डिपो',
  'plItemCode':'पीएल नंबर/आइटम कोड',

  //MISC
  'jumpButton': 'जंप बटन',
  'jumpButtonDesc': '20 आइटम को ऊपर और नीचे करने के लिए इन पर टैप करें',
  'select': 'चुनें',
  'totalloanreceipt': 'वापिस किये जाने वाले शेष लोन की मात्रा',
  'totalloanissue': 'वापिस प्राप्त किये जाने वाले शेष लोन की मात्रा',
  'whatsAppMsg': 'व्हाट्सएप मैसेज',
  'failedToLaunchWA': 'व्हाट्सएप लॉन्च करने में विफल',

  //Item receipt details
  'itemReceiptDetails': 'आइटम रसीद विवरण',
  'cdCode': 'सीoडीo कोड',
  'receivingDepot': 'रिसीविंग डिपो',
  'subDepot': 'उप डिपो',
  'plNoOfMaterial': 'प्राप्त सामग्री की पीoएलo संख्या',
  'demandAndIssueDetails': 'मांग और जारी करने का विवरण',
  'demandNo': 'मांग संख्या',
  'demandDate': 'मांग तिथि',
  'issueNoteNo': 'इशू नोट संख्या',
  'issueDepotShop': 'जारी करने वाला डिपो / दुकान',
  'issuingOfficial': 'जारी करने वाला अधिकारी',
  'allocationDetails': 'आवंटन विवरण',
  'allocationPGR': 'आवंटन पी/जी/आर/\nआदेश सं.',
  'workOrderNo': 'कार्य आदेश संख्या',
  'voucherDetails': 'वाउचर विवरण',
  'voucherNo': 'वाउचर संख्या',
  'voucherDate': 'वाउचर दिनांक',
  'descriptionTabs': '\t\t\t\t\t\t\t\t\t\t\t\t\t',
  'remarksTabs': '\t\t\t\t\t\t\t\t\t\t',
  //Advice Note
  'adviceNote': 'सलाह नोट',
  'dpcd': 'डीoपीoसीoडीo',
  'consignor': 'प्रेषक',
  'controllingOfficer': 'नियंत्रण अधिकारी',
  'allocationNo': 'आवंटन संo',
  'rmcCreditNote': 'आरoएमoसीo / क्रेडिट नोट नंo',
  'rmcCreditDate': 'आरoएमoसीo / क्रेडिट तिथि',
  'wagonNo': 'वैगन संo',
  'rrNo': 'आरoआरo संo',
  'wagonDate': 'वैगन दिनांक',
  'depotRemarks': 'डिपो टिप्पणियां',
  'dispatchDetails': 'प्रेषण विवरण',
  'approvingAuthority': 'स्वीकृति प्राधिकारी',
  'accountalDetails': 'खाता विवरण',
  'returningOfficial': 'रिटर्निंग ऑफिशियल',
  'receivingDate': 'प्राप्ति दिनांक',
  'officialDetails': 'आधिकारिक विवरण',
  'issuingDepot': 'जारी करने वाला डिपो',
  'quantityInWords': 'मात्रा (शब्दों में)',
  'sign': 'साइन',
  'depotShopCodeConsignee': 'डिपो / दुकान कोड / परेषिती / ठेकेदार',
  'detailsOfReceiptVoucher': 'रसीद वाउचर का विवरण',
  //Issue Note
  'issueNote': 'इश्यू नोट',
  'issueAndDemandDetails': 'इश्यू और मांग विवरण',
  //Warranty Claim For Rejected Item
  'depotLodgingWarranty': 'डिपो लॉजिंग वारंटी क्लेम',
  'warrantyClaimNo': 'वारंटी क्लेम संख्या',
  'warrantyClaimDate': 'वारंटी क्लेम दिनांक',
  'poContractNo': 'पीoओo अनुबंध संख्या',
  'poContractDate': 'पीoओo अनुबंध दिनांक',
  'depotOriginallyReceivingMaterial':
  'मूल रूप से सामग्री प्राप्त करने वाला डिपो',
  'subDepotSubConsignee': 'उप-डिपो /\nउप-प्रेषिती',
  'warrantyClaim': 'वारंटी दावा विवरण',
  'nameAndAddressOfSupplier': 'सप्लायर का नाम और पता',
  'challanNoDate': 'चालान संख्या /\nदिनांक',
  'billNoDate': 'बिल संख्या /\nदिनांक',
  'ddrNoDate': 'डीoडीoआरo संख्या /\nदिनांक',
  'islNoDate': 'आईoएसoएलo संख्या /\nदिनांक',
  'inspectionBy': 'द्वारा निरीक्षण',
  'qtyRejectedUnderWarranty': 'वारंटी के तहत खारिज की गई मात्रा',
  'qtyRejectedUnderWarrantyWords': 'वारंटी के तहत खारिज की गई मात्रा (शब्दों में)',
  'ratePerUnit': 'रेट / यूनिट',
  'valueOfRejectedItem': 'अस्वीकृत आइटम का मूल्य',
  'headPerAllocation': 'हेड / आवंटन',
  'warrantyClaimAmount': 'वारंटी क्लेम राशि',
  'recoveryAdvice': 'वसूली सलाह',
  'note': 'नोट',
  'accountingUnit': 'एकाउंटिंग यूनिट',
  'warrantyDetails': 'वारंटी विवरण',
  //Consignee Receipt Note
  'crnNo': 'सीआरएन संख्या',
  'firmDetails': 'फर्म का विवरण',
  'dmtrNo': 'डीएमटीआर संख्या',
  'packagesReceived': 'पैकेज प्राप्त',
  'poContractUnitRate': 'पीओ/अनुबंध इकाई दर (सभी सहित)',
  'itemQtyInPO': 'पीओ/अनुबंध में आइटम की मात्रा',
  'deliveryPeriod': 'वितरण अवधि',
  'qtyDisp': 'भेजी गई मात्रा \n(पीओ/अनुबंध इकाई में)',
  'qtyAcceptPO': 'स्वीकृत मात्रा \n(पीओ/अनुबंध इकाई में)',
  'qtyAcceptTU': 'स्वीकृत मात्रा \n(लेनदेन इकाइयों में)',
  'qtyRecPO': 'प्राप्त मात्रा \n(पीओ/अनुबंध इकाई में)',
  'qtyRejPO': 'अस्वीकृत मात्रा \n(पीओ/अनुबंध इकाई में)',
  'acceptedQtyVal': 'स्वीकृत मात्रा का मूल्य \n(रुपये में)',
  'demandAndIssue': 'मांग और निर्गम विवरण',
  'demandWorkSanction': 'मांग/कार्य स्वीकृति संख्या और \nतारीख',
  'challanDate': 'चालान संख्या और \nतारीख',
  'icDate': 'आईसी नंबर \n/दिनांक',
  'productSLDate': 'उत्पाद एसएल नं।',
  'receivingOfficial': 'प्राप्त करने वाला अधिकारी',
  'billingDetails': 'बिलिंग विवरण',
  'billPassing': 'बिल पासिंग',
  'allocation': 'आवंटन',
  'locationOfMatDuringRec': 'प्राप्ति के दौरान सामग्री का स्थान',
  'makeBrand': 'मेक/ब्रांड',
  'accountedInLedger': 'खाता बही में',
  'payingAuthority': 'भुगतान प्राधिकरण',
  'poContractAgency': 'पीओ / अनुबंध निरीक्षण एजेंसी',
  'paymentTerms': 'भुगतान की शर्तें:',
  'dateOfAccountal': 'लेखा की तिथि',
  'matStockLoc': 'सामग्री संग्रहण स्थान',
  'ledgerFolio': 'लेजर फोलियो',
  'somethingWentWrong': 'कुछ गड़बड़ है',
  'signatureOfStockHolder': 'स्टॉक होल्डर के हस्ताक्षर',
  //Online Bill Status
  'onlinebillstatus': 'ऑनलाइन बिल स्थिति',
  'podatefrom': 'पी.ओ दिनांक से',
  'podateto': 'पी.ओ दिनांक तक',
  'consigneerailway':'परेषिती रेलवे',
  'consigneerailway':'भुगतान प्राधिकरण रेलवे',
  'consigneedetails':'परेषिती विवरण',
  'entersearchcriteria':'खोज मानदंड दर्ज करें',
  'searchcriteria': 'पीoओo संख्या दर्ज करे / विक्रेता का नाम / विवरण ',
  'payingauthorityrailway':'भुगतान प्राधिकरण रेलवे',

  //online bill summary
  'on-lineBillSummary':'ऑनलाइन बिल सारांश',
  'billsubmissiondatefrom':'बिल जमा करने की दिनांक से',
  'billsubmissiondateto':'बिल जमा करने की दिनांक तक',
  'selectdepartment':'विभाग चुनें',
  'selectuserdepot':'उपयोगकर्ता डिपो का चयन करें',
  'payauth':'भुगतान प्राधिकारी',


  'billsubdate': 'बिल जमा करने की तिथि: से',
  'billsubdateto': 'बिल जमा करने की तिथि: तक',

  'uname': 'इकाई का नाम',
  'pono&date' :'पीओ संख्या और तिथि',
  'itemdes' : 'विवरण',
  'posr' : 'पीओ एसआई। नंबर',
  'dtype': 'दस्तावेज़ प्रकार',
  'docnodate' : 'दस्तावेज़ संख्या और दिनांक',
  'billnodate' : 'बिल नंबर और तारीख',
  'irepsbillnodate': 'आईआरईपीएस बिल नंबर और तारीख',
  'irepsbillsrno': 'आईआरईपीएस बिल क्रमांक',
  'billamt1': 'बिल राशि',
  'railname': 'रेलवे',

  'unitname': 'इकाई',
  'openbal':'प्रारंभिक जमा',
  'billreceived':'ऑन लाइन बिल रिकॉर्ड',
  'billreturned':'लौटाए गए बिल',
  'billpassed':'बिल पारित',
  'totalpending':'कुल लंबित बिल',
  'tttle':'                लंबित विधेयकों का विवरण',
  'pendsevendays':'< 7 दिन',
  'pendfifteendays':'7 से  15 दिन',
  'pendthirtydays':'15 से  30 दिन',
  'pendmorethirty':'>30 दिन',



  // CRN Summary
  'crndigisigned' : 'सीआरएन (डिजिटल रूप से हस्ताक्षरित)',
  'awaitingmyapproval' : 'मेरी स्वीकृति की प्रतीक्षा करें',
  'datefrom' : 'दिनांक से',
  'dateto' : 'दिनांक तक',
  'search' : 'खोजें',
  'crnsummary':'सी.आर.एन सारांश',
  'fromDate1':'पर्ची की तारीख से',
  'toDate1':'पर्ची की तारीख तक',
  'dropremarks' : 'ड्रॉप टिप्पणी',
  'userSubDepot2':'उपयोगकर्ता डिपो का चयन करें',
  'userSubDepot1':'उप परेषिती',
  'foewardedby' : 'द्वारा अग्रेषित',
  'myforwarded' : 'मेरा अग्रेषित',
  'myfinalised' : 'मेरे अंतिम मामले',
  'finalisedbyon' : 'अंतिम रूप दिया गया द्वारा/पर',
  'forwardedtoon' : 'अग्रेषित को/चालू',

  //CRC Digitally-signed
  'crcdigisigned' : 'सीआरसी (डिजिटल हस्ताक्षरित)',
  'awaitingapproval' : 'मेरी स्वीकृति की प्रतीक्षा में',
  'datefrom' : 'दिनांक से',
  'dateto' : 'दिनांक तक',
  'search' : 'खोजें',
  'finalizedme' : 'मेरे द्वारा अंतिम रूप दिया गया',
  'forwardedfrom' : 'से अग्रेषित',
  'vouchernumdate' : 'वाउचर नंबर और तारीख',
  'ponumdate' : 'पीओ संख्या और तिथि',
  'plnumitemcode' : 'पीएल नंबर/आइटम कोड',
  'vendorname' : 'विक्रेता का नाम',
  'itemdesc' : 'आइटम विवरण',
  'recdqty' : 'प्राप्त मात्रा',
  'recdvalue' : 'प्राप्त मूल्य(रु.)',
  'acceptqty' : 'स्वीकार मात्रा',
  'acceptvalue' : 'स्वीकार मूल्य(रु.)',
  'dropremarks' : 'ड्रॉप टिप्पणी',
  'status' : 'दर्जा',
  'action' : 'गतिविधि',
  'finalisedbyon' : 'अंतिम रूप दिया गया द्वारा/पर',
  'forwardedtoon' : 'अग्रेषित को/चालू',

  //--------------action page-------
  'qty': 'मात्रा.',
  'qty1': '',
  'payingrly': 'परेषिती रेलवे',

  'consrly': 'परेषिती रेलवे',
  'Consignee Code': 'परेषिती कोड',
  'poNO': 'पीओ संख्या और तिथि',
  'podate': '',
  'vendorname': 'विक्रेता का नाम',
  'poSiNo': 'पीओ क्रमांक',
  'itemdesc1': 'आइटम विवरण',
  'doctype': 'दस्तावेज़ प्रकार/                     (सीआरसी/सीआरएन/आर नोट)',
  'dmtrno': 'डीएमटीआर/आरओ नंबर और तारीख',
  'dmtrno1': '',
  'allocation': 'भुगतान रेलवे',
  'payingauthority': 'भुगतान प्राधिकरण',
  'billno': 'बिल संख्या और तिथि',
  'billno1': '',
  'billdate': 'आईआरईपीएस बिल नंबर और तारीख',
  'billdate1': '',
  'billtype': 'बिल प्रकार',
  'paymenttype': 'भुगतान के प्रकार',
  'paymentpercentage': 'भुगतान प्रतिशत',
  'itemno': 'बिल की मद संख्या',
  'billamt': 'मद के लिए बिल राशि (रु.)',
  'co6no': 'CO6 संख्या और तिथि',
  'co6date': '',
  'co7no': 'CO7 संख्या और तिथि',
  'co7date': '',
  'passedamtitem': 'मद के लिए पारित राशि (रु.)',
  'paydate': 'भुगतान तिथि',
  'tbillamt': 'कुल बिल राशि (रु.)',
  'passedmtbill': 'बिल के लिए पारित राशि (रु.)',
  'deductedamtbill': 'बिल के लिए कटौती राशि (रु.)',
  'paidamtbill': 'बिल के लिए भुगतान राशि (रु.)',
  'returnreason': 'वापसी वजह',
  'returndate': 'वापसी दिनांक',
  'payrly': 'भुगतान रेलवे',
  'rly': 'रेलवे',
  'frombill':  'बिल से',
  'co6status':  'Co6 स्थिति',
  'payauth1':  'भुगतान रेलवे',
  'rnotedate':  'आर नोट दिनांक',
  'rnoteno':  'आर नोट संख्या',

  'sacdetails' : 'स्टॉक, एएसी और खपत विवरण',
  'wd':'डब्ल्यू.डी',
  'cat': 'CAT',
  'mdp':'एमडीपी',
  'aac':'एएसी',
  'ncp' : 'राकांपा',
  'stock': 'स्टॉक (एमटीएचएस)',
  'spare': 'स्पेयर स्टॉक',
  'lidt':'एलआई डीटी',
  'lrdt':'एलआर डीटी',

  // Stock item history sheet
  'stkitemtitle' : 'स्टॉक आइटम इतिहास पत्रक',
  'tophead' : 'स्टॉक आइटम की वस्तु स्थिति (इतिहास पत्र)',
  'rly' : 'रेलवे:',
  'selectrly' : '--रेलवे चुनें--',
  'pldetails' : 'पीएल विवरण:',
  'hsmrly' : 'इतिहास पत्रक (मेरी रेलवे)',
  'hsarly' : 'इतिहास पत्रक (सभी रेलवे)',
  'clear' : 'हटाना',
  'exit' : 'बाहर निकलना',
  'find' : 'ढूंढना',
  'plhint' : 'खोजने के लिए PL/वस्तु विवरण के कुछ अक्षर टाइप करें',
  'rlysuggestion' : 'इतिहास पत्रक खोजने के लिए कृपया किसी रेलवे का चयन करें',
  'plsuggestion' : 'इतिहास पत्रक खोजने के लिए कृपया pl विवरण टाइप करें',
  'messagemyrly' : 'पहले से ही मेरे रेलवे का डेटा दिखा रहा है',
  'mesaageallrly' : 'पहले से ही सभी रेलवे का डेटा दिखा रहा है',
  'dnf' : 'डेटा नहीं मिला',
  'searchbtn' : 'खोजें...',
  'search' : 'खोजें',
  'plno' : 'पीएल नं.',
  'desc' : 'विवरण',

  'historysheet' : 'इतिहास पत्रक',

  'uncovereddue' : 'कवर नहीं किया गया बकाया विवरण',
  'depot' : 'डिपो',
  'demandnum' : 'मांग संख्या',
  'regdate' : 'पंजीकरण दिनांक',
  'dueqty' : 'देय मात्रा',
  'unit' : 'इकाई',
  'duedate' : 'नियत तारीख',
  'type' : 'टाइप',
  'filetendernum' : 'फ़ाइल/निविदा संख्या',
  'remarks' : 'टिप्पणियां',


  'rlyboardintent' : 'रेलवे बोर्ड इंडेंट कवरेज विवरण',
  'ponumname' : 'पी.ओ.सं./विक्रेता का नाम',
  'sr' : 'एसआर',
  'depot' : 'डिपो',
  'airate' : 'एआई दर',
  'poqty' : 'पीओ मात्रा',
  'unit' : 'इकाई',
  'dueqty' : 'देय मात्रा',
  'startdp' : 'डीपी शुरू करें',
  'delydt' : 'डेली.डीटी',
  'demnum' : 'डीम.सं.',

  'totalavl' : 'यूडीएम में उपयोक्ताओं/कंसाइनी द्वारा अनुरक्षित डिजिटल लेजर में चयनित मद का कुल उपलब्ध स्टॉक',

  'covereddue' : 'कवर की गई बकाया राशि का विवरण',
  'accmaterialdetail' : 'लेखा के तहत सामग्री का विवरण',
  'srnum' : 'क्रमांक',
  'recieptdet' : 'रसीद विवरण',

  'cancqty' : 'रद्द मात्रा',
  'rejqty' : 'अस्वीकृत मात्रा',
  'recqty' : 'स्वीकृत मात्रा',
  'orgdp' :  'संगठन डी.पी',
  'startdp' : 'डीपी शुरू करें',
  'extdp' : 'एक्सट.डीपी',
  'postatus' : 'पीओ स्थिति',

  'overstock' : 'अन्य रेलवे में अधिक स्टॉक/अधिशेष/निष्क्रिय',
  'ward' : 'Ward',

  'plnum' : 'पी एल संख्या',
  'oldplnum' : 'पुराना प्ल संख्या',
  'uniplnum' : 'यूनी पीएल संख्या',
  'desc' : 'विवरण',
  'uniyn' : 'यूनी_वाईएन',
  'sec' : 'Sec',
  'file' : 'फ़ाइल',
  'cp' : 'सीपी',
  'srs' : 'एसआरएस',
  'vitsaf' : 'विट/सफ',
  'abc' : 'एबीसी',
  'pasnct' : 'पीएएस.एनसीटी',
  'mustchg' : 'चाहिए',
  'self' : 'दराज',
  'source' : 'स्रोत',
  'unfrly' : 'यूएनएफ.रेलवाई',
  'wtkg' : 'वजन केजी',

  'totconhed' : 'कुल (खपत)',
  'aacncp' : 'एएसी एएसी एनसीपी',

  //====history sheet======

  'consales':'उपभोग/बिक्री',
  'stockmonth':'स्टॉक(एमटीएचएस)',
  'brate':'बी.रेट',
  'year' : "वर्ष",
  '1819':'वर्ष(18-19)',
  '1920':'वर्ष(19-20)',
  '2021':'वर्ष(20-21)',
  '2122':'वर्ष(21-22)',
  '2223':'वर्ष(22-23)',


  //===========posearch================

  'receipt' : 'रसीद विवरण देखें',
  'totalqtydis' : 'कुल मात्रा। भेजा गया',
  'tqtyrecieved': 'कुल मात्रा। प्राप्त हुआ',
  'tqtyaccepted': 'कुल मात्रा। को स्वीकृत',
  'tqtyrejeted': 'कुल मात्रा। अस्वीकृत',
  'twtyrejection': 'कुल वारंटी अस्वीकृति',
  'initialrejection': 'प्रारंभिक अस्वीकृत मात्रा। पुन: निरीक्षण में स्वीकार किया गया',
  'warrantyrejection': 'वारंटी अस्वीकृत मात्रा। पुन: निरीक्षण में स्वीकार किया गया',
  'supplysummary': '             आपूर्ति सारांश',
  'DMTR No. & Date': 'डीएमटीआर संख्या और दिनांक',
  'Challan No. & Date': 'चालान संख्या और दिनांक',
  'Make / Brand': 'मेक / ब्रांड',
  'Product Sr. No.': 'उत्पाद क्रमांक',
  'Warranty upto': 'वारंटी तक',
  'Qty. Dispatched': 'मात्रा भेजा गया',
  'QtyReceived': 'मात्रा प्राप्त हुआ',
  'Qty. Accepted': 'मात्रा को स्वीकृत',
  'Initial Rejection': 'प्रारंभिक अस्वीकृति',
  'Warranty Rejection': 'वारंटी अस्वीकृति',
  'Re-Insp. Qty': 'पुन: निरीक्षण मात्रा',
  'Returned Qty. to Vendor': 'लौटाई गई मात्रा। विक्रेता को',
  'Qty. taken into Ledger': 'मात्रा लेजर में लिया गया',
  'Transaction Status': 'लेन-देन की स्थिति',
  'Action': 'गतिविधि',
  'Purchase Order / Contract Supply Status': 'खरीद आदेश/अनुबंध आपूर्ति की स्थिति',
  'Railway': 'रेलवे',
  'Consignee Code': 'परेषिती कोड',
  'PO / Contract No.': 'पीओ/अनुबंध संख्या',
  'PO / Contract Date': 'पीओ / अनुबंध तिथि',
  'Item Sl. No. in PO / Contract': 'मद क्रमांक पीओ / अनुबंध में संख्या',
  'Item Description': 'आइटम विवरण',
  'Vendor Name': 'विक्रेता का नाम',
  'Quantity': 'मात्रा',
  'heading': 'केवल वे इश्यू/रसीद लेनदेन दिखाए जाते हैं जो यूडीएम में बनाए गए डिजिटल लेजर में किए जाते हैं।',
  'dtlsissue':'मुद्दों का विवरण',
  'RcptDetails':'रसीद विवरण',
  'issuedtls':'जारी करने का विवरण',
  'ttlissue':'कुल मुद्दे',
  'blc':'संतुलन',
  'viewissuedetails':'समस्या विवरण देखें',
  'dtsissue':'मुद्दों का विवरण',
  'unitrate':'यूनिट दर',
  'vocherno':'वाउचर संख्या।',
  'actdate':'लेखा तिथि',
  'qty':'मात्रा',
  'makebrand':'मेक / ब्रांड',
  'prdtslno':'उत्पाद क्रमांक',
  'warrantyupto':'वारंटी तक',
  'issuenotedate':'अंक नोट संख्या और दिनांक',
  'iisueqty':'जारी मात्रा',
  'blcqty':'शेष मात्रा',
  'Consignee Code1':'',
  'chDate':'',
  'heading1': 'केवल वे इश्यू/रसीद लेनदेन दिखाए जाते हैं जो यूडीएम में बनाए गए डिजिटल लेजर में किए जाते हैं।',


  'coveredduedetail' : 'कवर की गई बकाया राशि का विवरण',

  'matunderacc' : 'लेखापरीक्षा के अंतर्गत सामग्री का विवरण',
  'recdet' : 'रसीद विवरण',

  'materialrejected' : 'अस्वीकृत सामग्री का विवरण',

  'intentdetail' : 'आशय विवरण',
  'intentpurnum' : 'इंडेंट नंबर/पूरा एजेंसी',
  'indqty' : 'इंडस्ट्रीज़ मात्रा',
  'unit' : 'इकाई',
  'cvdqty' : 'सीवीडी मात्रा',
  'delydt' : 'डेली.डीटी',
  'dueqty' : 'देय मात्रा',

  'intentnumpur' : 'इंडेंट नंबर/खरीद एजेंसी',

  'rejectdtl' : 'अस्वीकृति विवरण',

  'pw' : 'कृपया प्रतीक्षा करें...',
  'refresh' : 'ताज़ा करना',

  // --- view details show ---

  'viewconsumption' : 'स्टॉक और खपत विवरण का विवरण देखने के लिए क्लिक करें',
  'viewuncovered' : 'कवर न किए गए देय विवरण का विवरण देखने के लिए क्लिक करें',
  'viewintent' : 'इंडेंट विवरण का विवरण देखने के लिए क्लिक करें',
  'viewrlyboard' : 'रेलवे बोर्ड इंडेंट कवरेज विवरण का विवरण देखने के लिए क्लिक करें',
  'viewcovereddue' : 'कवर किए गए देय विवरण का विवरण देखने के लिए क्लिक करें',
  'viewmaterialunderaccountal' : 'लेखापरीक्षा के तहत सामग्री का विवरण देखने के लिए क्लिक करें',
  'viewmaterialrejected' : 'अस्वीकृत सामग्री का विवरण देखने के लिए क्लिक करें',
  'vieworderplace' : 'पिछले 5 वर्षों के दौरान दिए गए आदेशों का विवरण देखने के लिए क्लिक करें',
  'viewoverstock' : 'अन्य रेलवे में ओवर स्टॉक/सरप्लस/निष्क्रिय का विवरण देखने के लिए क्लिक करें',

  'consumptionsnackertitle' : 'क्या आप कुल खपत विवरण देखना चाहते हैं?',
  'snackerview' : 'देखें',

  'savedpdf' : 'डाउनलोड करें और रसीद सहेजें',
  'stdwnd' : 'डाउनलोड करना शुरू हो गया...',

  // --- Non-Stck Demands ---
  'nonstocktitle' : 'गैर-स्टॉक मांगें',
  'dashboard' : 'डैशबोर्ड',
  'fwdfnd' : 'मेरे द्वारा अग्रेषित/अंतिम रूप दिया गया',
  'awaitingaction' : 'मेरे कार्य की प्रतीक्षा में',
  'casetracker' : 'केस ट्रैकर',
  'status' : 'दर्जा',
  'demandno' : 'मांग संख्या',
  'indentor' : 'मांगकर्ता',
  'consignee' : 'परेषिती',
  'dmddtfrom' : 'मांग की तारीख से',
  'dmddtto' : 'डिमांड डेट टू',
  'itemdesc' : 'आइटम विवरण',
  'proceed' : 'आगे बढ़ना',
  'reset' : 'रीसेट',
  'dmdnodt' : 'मांग संख्या और दिनांक',
  'itemdetails' : 'आइटम विवरण',
  'valuemav' : 'मूल्य और न्यूनतम। स्वीकृति स्तर',
  'crnwith' : 'वर्तमान में साथ',
  'action' : 'गतिविधि',
  'dfctd' : 'मांग/फाइल/मामला/निविदा संख्या/विवरण',
  'prorly' : 'रेलवे खरीद रहा है',
  'itemsr' : 'आइटम और क्र.सं.',
  'stknon' : 'स्टॉक/गैर-स्टॉक',
  'casefile' : 'मामला/फाइल सं.',
  'tendercls' : 'निविदा संख्या और समापन तिथि',
  'selectsts' : '---स्थिति का चयन करें---',
  'selectcons' : '---परेषिती का चयन करें---',
  'selectsubcons' : '---उप-परेषिती का चयन करें---',
  'selectdept' : '--- विभाग का चयन करें ---',
  'selectindentor' : '--- इंडेंटर चुनें ---',
  'dmdvalue' : 'मांग मूल्य (रुपये)',
  'purpose' : 'उद्देश्य',
  'fundavlyear' : 'निधि उपलब्धता वर्ष',
  'spni' : 'सुरक्षा/यात्री आवश्यकता वस्तु?',
  'wac' : 'क्या पीएसी केस?',
  'idr' : 'मांगकर्ता मांग संदर्भ',
  'sen' : 'विभिन्न अनुमान संख्या',
  'ed' : 'अनुमानित तिथि',
  'ein' : 'अनुमानित आइटम नंबर',
  'pt' : 'खरीद का प्रकार',
  'pu' : 'क्रय इकाई',
  'itemdet' : 'आइटम विवरण',
  'vaa' : 'विक्रेता अनुमोदन एजेंसी',
  'tq' : 'कुल मात्रा.',
  'raters' : 'दर (रु.)',
  'valuers' : 'मूल्य (रु.)',
  'consignee' : 'परेषिती',
  'qty' : 'मात्रा',
  'state' : 'राज्य',
  'reqat' : 'पर आवश्यक है',
  'inhandqty' : 'हाथ में मात्रा.',
  'drb' : 'डिलिवरी अपेक्षित. द्वारा',

  //--------Rejection/Warranty UI-------

  'rwtitle' : 'अस्वीकृति/वारंटी',
  'rwwarantycmptitle' : 'वारंटी शिकायत डेटा',
  'fwctitle' : 'मेरे अग्रेषित दावे',
  'apdtitle' : 'मेरे स्वीकृत/छोड़े गए दावे',
  'wcp' : 'अवधि से वारंटी का दावा',
  'pt' : 'अवधि के लिए',
  'fromdate' : 'दिनांक से',
  'todate' : 'दिनांक तक',
  'status' : 'दर्जा',
  'rwsearch' : 'खोजें',
  'rwsearchhint' : 'कृपया वारंटी दावा संख्या/DMTR संख्या/आइटम कोड/आइटम विवरण दर्ज करें',
  'rwexit' : 'बाहर निकलें',
  'rwsource' : 'स्रोत',
  'rwcmpform' : 'से शिकायत',
  'rwcmpref' : 'शिकायत संदर्भ',
  'rwpono' : 'पीओ संख्या',
  'rwvendorname' : 'विक्रेता का नाम',
  'rwposr' : 'पीओ सीनियर',
  'rwstkns' : 'स्टॉक/एन.एस',
  'rwplno' : 'पीएल संख्या',
  'rwitemdesc' : 'वस्तु वर्णन',
  'rwqty' : 'मात्रा',
  'rwinsagency' : 'निरीक्षण एजेंसी',
  'rwapproagency' : 'स्वीकृति एजेंसी',

  'wcref' : 'वारंटी दावा संख्या और अस्वीकृति/आपूर्ति संदर्भ',
  'pocontract' : 'पीओ-अनुबंध संख्या और दिनांक/चालान संख्या और दिनांक',
  'rejqty' : 'अस्वीकृत मात्रा',
  'rwrate' : 'दर (रु.)',
  'rwvalue' : 'मूल्य (रु.)',
  'rwftodate' : 'दिनांक को अग्रेषित किया गया',
  'badresp' : 'सर्वर से खराब प्रतिक्रिया',
  'refnow' : 'अब ताज़ा करें',
  'tryagain' : 'पुनः प्रयास करें',
  'monthwarning' : 'रिकॉर्ड दिखाने के लिए अमान्य प्रारंभ और समाप्ति तिथि',
  'rwalert' : 'चेतावनी!',
  'rwmonthwrtitle' : "क्षमा करें, आप प्रारंभ दिनांक से समाप्ति दिनांक तक छह माह से अधिक का डेटा नहीं देख सकते.",

  //=========================gemorder==========================
  'gemorderdtl' : 'जीईएम आदेश विवरण',
  'gemorderno' : 'जीईएम आदेश संख्या :',
  'search1' : 'खोज',
  'gemhint' : 'GEMC-511687702',
  'oredrid' : 'कृपया ऑर्डर आईडी दर्ज करें',

  'buyerdetails' : 'खरीदार विवरण',
  'org' : 'संगठन',
  'buyername' : 'खरीदार का नाम',
  'buyeradrs' : 'खरीदार का पता',
  'mobno' : 'मोबाइल नंबर',

  'gemorderdetails' : 'जीईएम आदेश विवरण' ,
  'ordernodate' : 'आदेश संख्या और आदेश दिनांक' ,
  'venname' : 'विक्रेता का नाम' ,
  'venpangstn' : 'विक्रेता पैन और जीएसटीएन' ,
  'noofitem' : 'वस्तुओ की संख्या' ,
  'orderamt' : 'आदेश राशि (रु)' ,
  'aucode' : 'एयू कोड' ,
  'accountingunit' : 'लेखा इकाई' ,
  'paymentmode' : 'भुगतान का प्रकार' ,

  'consdetails' : 'प्रेषिती विवरण' ,
  'sno' : 'क्र.सं.' ,
  'consname' : 'प्रेषिती का नाम' ,
  'consadd' : 'प्रेषित करने वाले का पता' ,
  'mobno' : 'मोबाइल नंबर' ,
  'itemdtls' : 'आइटम विवरण' ,
  'sino' : 'क्र.सं.' ,
  'des' : 'विवरण' ,
  'qty' : 'मात्रा' ,

  'covpodtls' : 'पीओ विवरण को कवर करना' ,
  'pono' : 'पीओ संख्या' ,
  'podate' : 'पीओ तिथि' ,
  'venname' : 'विक्रेता का नाम' ,
  'povalue' : 'पीओ मूल्य' ,
  'payauth' : 'भुगतान प्राधिकरण' ,

  'matrecaccdtls' : 'सामग्री रसीद / लेखा विवरण' ,
  'cons' : 'परेषिती' ,
  'dmtrrecnodate' : 'डीएमटीआर/डीआरआर नंबर और रसीद की तारीख' ,
  'doctype1' : 'दस्तावेज़ का प्रकार' ,
  'ronodate' : 'आरओ संख्या और दिनांक' ,
  'dispqty' : 'भेजी गई मात्रा' ,
  'receqty' : 'प्राप्त मात्रा' ,
  'accptqty' : 'स्वीकृत मात्रा।' ,
  'rejecqty' : 'अस्वीकृत मात्रा।' ,

  'billdtlsgemportal' : 'सीआरएसी और जीईएम बिल विवरण जीईएम पोर्टल पर जनरेट किए गए हैं' ,
  'consname' : 'प्रेषिती का नाम' ,
  'invoicenodate' : 'चालान संख्या और दिनांक' ,
  'cracdtls' : 'सीआरएसी विवरण' ,
  'billnodate' : 'बिल संख्या और दिनांक' ,
  'billamts' : 'बिल राशि (रु.)' ,
  'co6numdate' : 'CO6 संख्या और दिनांक' ,
  'co7numdate' : 'CO7 संख्या और दिनांक' ,
  'passamts' : 'पारित राशि (रु)' ,
  'dedamts' : 'कटौती की गई राशि (रु.)' ,
  'paydate' : 'भुगतान तिथि' ,
  'redate' : 'वापसी दिनांक' ,
  'rereasons' : 'रिटर्न वजह',

  'dedamtdtls' : 'आईपीएएस में कटौती की गई राशि का विवरण' ,
  'sno' : 'क्र.सं.' ,
  'dtlsded' : 'कटौती का विवरण' ,
  'amtsr' : 'राशि (रु.)' ,
  'dedhead' : 'कृपया जीईएम पोर्टल पर उत्पन्न सीआरएसी और जीईएम बिल विवरण देखने के लिए यहां क्लिक करें',
  'dmtrdate' : 'रसीद तारीख',

  //------ NS Demand Summary -------
  'nsdemandtitle' : 'एनएस डिमांड सारांश',
  'nsdatefrom' : 'एनएस मांग तिथि: से',
  'nsdateto' : 'एनएस मांग तिथि: तक',
  'nsdrailway' : 'रेलवे',
  'nsdunittype' : 'इकाई प्रकार',
  'nsdunitname' : 'इकाई का नाम',
  'nsddepartment' : 'विभाग का चयन करें',
  'nsdconsignee' : 'इंडेंटिंग कंसाइनी कोड',
  'nsdindentor' : 'मांगकर्ता का नाम',
  'nsdsubmit' : 'प्रस्तुत करना',
  'plNoErrorText1' : 'कृपया खोज मानदंड दर्ज करें',

  'nsdrly' : 'रेलवे',
  'nsdunittype' : 'इकाई प्रकार',
  'nsdunitname' : 'इकाई का नाम',
  'nsddept' : 'विभाग',
  'nsdcon' : 'इंडेंटिंग कंसाइनी',
  'nsdindentor' : "मांगकर्ता का नाम",
  'total' : 'संपूर्ण',
  'drf' : 'ड्राफ्ट स्टेज में',
  'ufc' :  'वित्त सहमति के तहत',
  'ufv' : 'वित्त पुनरीक्षण के तहत',
  'underprc' : 'प्रक्रिया के तहत',
  'apfwd' : 'स्वीकृत और खरीद के लिए अग्रेषित',
  'rtpurchase' : 'खरीद इकाई द्वारा लौटाया गया',
  'dropped' : 'छोड़ा हुआ',

  'dmdnumdate' : 'मांग संख्या और दिनांक',
  'indetortitle' : 'मांगकर्ता',
  'itemdetails' : 'आइटम विवरण',
  'valueminappr' : 'मूल्य और न्यूनतम। स्वीकृति स्तर',
  'purunit' : 'खरीद इकाई',
  'currentlywith' : 'वर्तमान में साथ',
  'status' : 'दर्जा',
  'viemdmd' : 'मांग देखें',
  'sdnf' : 'क्षमा करें, दस्तावेज़ नहीं मिला',
  'pdls' : 'पीडीएफ दस्तावेज़ सफलतापूर्वक लोड हो गया!',
  'docend' : 'दस्तावेज़ समाप्त!',

  //warranty Complaint
  'warrantycomsum' : 'वारंटी शिकायत सारांश',
  'cfrom': 'शिकायतें से :',
  'cto': 'शिकायतें तक:',
  'csource': 'शिकायत स्रोत',
  'ccodegencom': 'कंसाइनी कोड जनरेटिंग शिकायतें',
  'rlc': 'रेलवे टू लॉज क्लेम',
  'concodelc': 'दावा दर्ज करने के लिए परेषिती कोड',
  'submit': 'जमा करना',
  'reset': 'रीसेट',
  'compsource': 'शिकायत स्रोत',
  'rlgencomplaint': 'रेलवे जनरेटिंग शिकायत',
  'rlyvendor': 'वेंडर पर वारंटी का दावा दायर करेगा रेलवे',
  'complaint': 'शिकायत',
  'total': 'कुल',
  'lodgevendor': 'जहां विक्रेता पर दावा दायर किया गया',
  'initiatedvendor': 'जहां विक्रेता पर दावा शुरू किया गया',
  'retmaintapp': 'अनुरक्षण आवेदन पर लौटा',
  'apvvendor': 'जहां वेंडर पर दावा दर्ज करने के लिए स्टोर डिपो को मंजूरी देने के लिए सलाह नोट',
  'initiatedvendor': 'जहां वेंडर पर दावा दर्ज करने के लिए स्टोर डिपो को सलाह नोट शुरू किया गया',
  'returnedvendor':'जहां विक्रेता पर दावा दर्ज किए बिना स्टोर डिपो द्वारा सलाह नोट वापस कर दिया गया',
  'actioninitiated':'जहां अभी तक कार्रवाई शुरू नहीं हुई है',
  'warrantycom':'शिकायत सारांश',
  'source':'स्रोत',
  'complaintrailway':'शिकायत रेलवे',
  'complaintconsginee':'शिकायत प्रेषिती',
  'railwaylodgeclaim':'रेलवे टू लॉज क्लेम',
  'consgineelodgeclaim':'कंसाइनी टू लॉज क्लेम',
  'rejection':'अस्वीकृति संदर्भ',
  'plno':'पीएल सं।',
  'item':'वस्तु',
  'qty':'मात्रा',
  'vendor':'वेदोर',
  'status':'दर्जा',
  'claimno':'दावा संख्या',
  'claimdate':'दावा तिथि',
  'claimamount':'दावा राशि',

  // ------ Stocking Proposal Summary Screen ------
  'stkprptitle' : 'स्टॉकिंग प्रस्ताव सारांश',
  'stkprfromdate' : 'स्टॉकिंग प्रस्ताव तिथि: से',
  'stkprtodate' : 'स्टॉकिंग प्रस्ताव दिनांक: तक',
  'stksummaryrly' : 'रेलवे',
  'stksummarydept' : 'विभाग',
  'unitinitprpsl' : 'इकाई पहल प्रस्ताव',
  'unifyingrly' : 'एकीकृत रेलवे',
  'storedepot' : 'स्टोर डिपो',
  'totprpinit' : 'कुल प्रस्ताव शुरू किया गया',
  'prpindrfdatege' : 'मसौदा चरण में प्रस्ताव',
  'prpother' : 'विभागों के पास प्रस्ताव स्टोर के अलावा',
  'prpstrdepot' : 'स्टोर डिपो के साथ प्रस्ताव',
  'prppcm' : 'पीसीएमएम कार्यालय के पास प्रस्ताव',
  'prpunifrly' : 'रेलवे को एकीकृत करने के प्रस्ताव',
  'prprejected' : 'रेलवे को एकीकृत करके प्रस्तावों को खारिज कर दिया',
  'prpreturned' : 'प्रस्ताव सर्जक को लौटाए गए',
  'stcprpdrop' : 'स्टॉकिंग प्रस्ताव गिरा दिया',
  'stkprpapp' : 'स्टॉकिंग प्रस्ताव स्वीकृत',
  'stkappnumdate' : 'स्टॉकिंग आवेदन संख्या और दिनांक',
  'plsubgroup' : 'पीएल समूह / उप-समूह',
  'itemdesc' : 'वस्तु का विवरण',
  'stkinitiatorname' : "आरंभकर्ता का विवरण",
  'currentwith' : 'वर्तमान में साथ',
  'status' : 'दर्जा',



  //CRN Summary
  'crnsum':'सीआरएन सारांश',
  'rcptdatefrom':'प्राप्ति तिथि: से',
  'rcptdateto':'प्राप्ति तिथि: तक',
  'rly':'रेलवे',
  'unittype':'इकाई प्रकार',
  'unitname':'इकाई का नाम',
  'slctdepart':'विभाग का चयन करें',
  'slctuserdepo':'उपयोगकर्ता डिपो का चयन करें',
  'subcons':'उप परेषिती',
  'r1':'रेलवे',
  'depart':'विभाग',
  'cons&subcons':'कंसाइनी और सब-कंसाइनी',
  'openbalence':'ओपनिंग बैलेंस (खेप जहां डिजिटल रूप से हस्ताक्षरित सीआरएन लंबित है)',
  'newconsrecvd':'नई खेप प्राप्त हुई',
  'conswheredigisign':'खेप जहां डिजिटल रूप से हस्ताक्षरित सीआरएन जारी किए गए',
  'closebalnc':'अंतिम शेष (खेप जहां डिजिटल रूप से हस्ताक्षरित सीआरएन लंबित है)',
  'breakuoppen':'लंबित डिजिटली-हस्ताक्षरित सीआरएन का ब्रेक-अप',
  '7days':'<7 दिन',
  '7to15':'7 से 15 दिन',
  '15to30':'15 से 30 दिन',
  '30d':'>30 दिन',
  'ponumdate':'पीओ संख्या और दिनांक',
  'venname':'विक्रेता का नाम',
  'poser':'पीओ एसआर.',
  'des1':'विवरण',
  'datereceipt':'प्राप्ति की तिथि',
  'dmtrnum':'डीएमटीआर संख्या और दिनांक',
  'qtyrecvd':'मात्रा। प्राप्त',
  'qtyacpt':'मात्रा। को स्वीकृत',
  'val1':'मूल्य (रु.)',
  'curstatus':'वर्तमान स्थिति',

  // ---- Warranty Rejection Register -----
  'wrrtitle':'वारंटी अस्वीकृति रजिस्टर',
  'wcfp' : 'अवधि से वारंटी का दावा',
  'pt' : 'अवधि के लिए',
  'sv' : 'खोज विक्रेता',
  'wrrsearch' : 'खोज',
  'svhint' : 'कृपया विक्रेता का नाम लिखें',
  'shint' : 'कृपया वारंटी दावा संख्या/DMTR संख्या/आइटम कोड/आइटम विवरण दर्ज करें',
  'wrrall' : "सभी",
  'wrrpenr' : 'लंबित वसूली',
  'wrrnilrcr' : 'निल रिकवरी',
  'wrrretvendor' : 'विक्रेता को वापस की जाने वाली सामग्री (शून्य वसूली)',
  'wrrsubmit' : 'खोज',
  'wrrexit' : 'बाहर निकलना',

  'wcrrd' : 'वारंटी दावा और रसीद/अस्वीकृति विवरण',
  'vendor' : 'विक्रेता का नाम',
  'wrrponumdate' : 'पीओ-अनुबंध संख्या और दिनांक/चालान संख्या और दिनांक',
  'itemdesc' : 'आइटम विवरण',
  'qrcwwb' : 'मात्रा अस्वीकृत/वापस लिया गया दावा/शेष.रेज.उपलब्ध',
  'qrarrr' : 'मात्रा पुन: निरीक्षण/स्वीकार करें। (पुनः निरीक्षण)/लौटाया/बदला गया',
  'orwarabr' : 'मूल वसूली/रिकोव.राशि/बैलेंस.रिकवरी',
  'vorqbrqau' : 'मूल्य मूल.अस्वीकार.मात्रा/शेष राशि.अस्वीकृत.मात्रा/खाता इकाई',
  'rrrml' : 'अस्वीकृति का कारण/अस्वीकृत सामग्री स्थान',
  'action' : 'कार्य',

  'twcao' : 'कुल वारंटी दावा राशि (मूल)',
  'twcac' : 'कुल वारंटी दावा राशि (वर्तमान)',

  'swcf' : 'वारंटी दावा का सारांश से:',
  'wrrto' : 'तक:',

  'wra' : 'वारंटी अस्वीकृति सलाह',
  'ratitle' : 'अस्वीकृति सलाह',
  'wran' : 'वारंटी अस्वीकृति सलाह सं.',
  'ran' : 'अस्वीकृति सलाह सं.',
  'pocn' : 'पीओ/अनुबंध सं.',
  'pocd' : 'पीओ/अनुबंध तिथि',
  'isrpoc' : 'मद क्र.सं. पीओ/अनुबंध में',
  'crr' : 'परेषिती रिपोर्टिंग अस्वीकृति:',
  'sdsc' : 'सब-डिपो/सब-कंसाइनी:',
  'cn' : 'शिकायत संख्या:',
  'rarn' : 'अस्वीकृति सलाह पंजीकरण संख्या:',
  'cd' : 'शिकायत दिनांक:',
  'nas' : 'आपूर्तिकर्ता का नाम और पता:',
  'cnum' : 'चालान-सं.:',
  'cnumd' : 'चालान तिथि:',
  'icnum' : 'आईसी-संख्या:',
  'icd' : 'आईसी दिनांक:',
  'islnum' : 'आईएसएल-नंबर:',
  'isld' : 'आईएसएल दिनांक:',
  'drrn' : 'डीआरआर-नंबर:',
  'drrd' : 'डीआरआर दिनांक:',
  'dds' : 'विवरण और दवा/विशेष।',
  'pnic' : 'पी एल संख्या/आइटम कोड:',
  'iby' : 'द्वारा निरीक्षण:',
  'icn' : 'आईसी नं',
  'vaa' : 'विक्रेता अनुमोदन एजेंसी:',
  'qr' : 'मात्रा अस्वीकृत:',
  'qrw' : 'अस्वीकृत मात्रा (शब्दों में):',
  'ror' : 'अस्वीकृति का कारण:',
  'ru' : 'दर/यूनिट:',
  'ha' : 'शीर्ष/आवंटन:',
  'camt' : 'दावा राशि:',
  'ra' : 'वसूली-सलाह:',
  'note' : 'टिप्पणी:',
  'rfia' : 'निरीक्षण एजेंसी के लिए टिप्पणियां:',
  'cpa' : 'संबंधित भुगतान प्राधिकरण:',
  'sdo' : 'दुकान/डिपो अधिकारी',
  'co' : 'नियंत्रण अधिकारी',

  'wr' : 'वापस लिया गया संदर्भ',
  'qw' : 'मात्रा। वापस लिया गया',
  'duc' : 'उपयोगकर्ता डिपो/परेषिती का विवरण',
  'dad' : 'डिजिटल प्राधिकरण दस्तावेज़',

  'rivnum' : 'पुन: निरीक्षण वाउचर संख्या',
  'dpri' : 'पुन: निरीक्षण के लिए प्रस्तुत करने की तिथि',
  'dri' : 'मात्रा। पुन: निरीक्षण के लिए प्रस्तुत करें',
  'qari' : 'मात्रा। पुन: निरीक्षण के बाद स्वीकार किया गया',
  'dari' : 'पुन: निरीक्षण के बाद लेखा की तिथि',
  'dudc' : 'उपयोगकर्ता डिपो/परेषिती का विवरण',
  'dcsd' : 'डिजिटल सीआरएन स्थिति/दस्तावेज',
  'mb' : 'मेक/ब्रांड:',
  'bpsn' : 'बैच/उत्पाद क्र.सं. संख्या',
  'wp' : 'वारंटी अवधि:',
  'adpymt' : 'अग्रिम भुगतान:',

  'ddars' : 'प्रतिस्थापन आपूर्ति के लेखांकन की डीएमटीआर संख्या और तारीख',
  'qtyr' : 'मात्रा.बदला गया',
  'scnd' : "आपूर्तिकर्ता का चालान नंबर और तारीख",
  'drrs' : 'प्रतिस्थापन आपूर्ति की प्राप्ति की तिथि',

  'frbd' : "फर्म का रिफंड बिल विवरण",
  'rr' : 'रेलवे रिफंड कर रहा है',
  'amtrr' : 'वापस की गई राशि (रु.)',
  'refd' : 'धनवापसी विवरण',

  'rrvn' : 'रिकवरी रिफंड वाउचर नं.',
  'rrvd' : 'रिकवरी रिफंड वाउचर दिनांक',
  'rrar' : 'रिकवरी रिफंड राशि (रु.)',
  'rrvdoc' : 'रिकवरी रिफंड वाउचर दस्तावेज़',

  'innd' : 'जारी नोट संख्या एवं दिनांक',
  'qtyret' : 'मात्रा.लौटाया गया',
  'srnd' : "आपूर्तिकर्ता का संदर्भ संख्या और दिनांक",
  'gpd' : 'गेट पास विवरण',
  'issuenote' : 'नोट जारी करें',

  'rmndnumdos' : 'अस्वीकृति मेमो नंबर और तारीख/डीएमटीआर नंबर और आपूर्ति की तारीख',
  'itemdescrs' : 'आइटम विवरण/पुनर्प्राप्ति स्थिति',
  'qtysplyaccrbrq' : 'मात्रा. प्रदाय/स्वीकृत/अस्वीकृत/बाल.रिज.मात्रा।',
  'triqtrq' : 'कुल पुनः निरीक्षण. मात्रा/कुल लौटाई गई मात्रा।',
  'rorraba' : 'मूल पुनर्प्राप्ति/पुनर्प्राप्ति को रेट करें। राशि/शेष वसूली',

  'tora' : 'कुल मूल वसूली राशि',
  'tcra' : 'कुल वर्तमान वसूली राशि',
  'tvoorq' : 'मूल अस्वीकृत मात्रा का कुल मूल्य',
  'tvobrq' : 'अस्वीकृत शेष राशि का कुल मूल्य',

  'condepot' : 'कंसाइनी डिपो',
  'viewwrntyclaim' : 'वारंटी दावा देखें',

  //---------CRC Summary----------------
  'crcsum':'सीआरसी सारांश',
  'grandtotal' : 'कुल योग',
  'openbalencecrc':'प्रारंभिक शेष (खेप जहां डिजिटल हस्ताक्षरित सीआरसी लंबित है)',
  'conswheredigisigncrc':'खेप जहां डिजिटल हस्ताक्षरित सीआरसी जारी किए गए',
  'closebalnccrc':'समापन शेष (खेप जहां डिजिटल हस्ताक्षरित सीआरसी लंबित है)',
  'breakuoppencrc':'लंबित डिजिटल हस्ताक्षरित सीआरसी का विवरण',
  'depttitle' : 'विभाग',
  'userdepotconsignee' : 'उपयोगकर्ता डिपो/कंसाइनी',
  'subconsignee' : 'उप-कंसाइनी',
  'desccrc' : 'विक्रेताओं द्वारा आपूर्ति की गई गैर-स्टॉक वस्तुओं के लिए डिजिटल रूप से हस्ताक्षरित सीआरसी का सारांश',
  'posason' : 'स्थिति यथावत',
  'crcto' : 'तक',
  'totvaluers' : 'कुल योग',
  'listingtype' : 'सूचीकरण का प्रकार:',

  //---------To End User Screen----------------
  'endusertitle' : 'अंतिम उपयोगकर्ता के लिए',
  'ledgerno' : 'लेजर नं.',
  'ledgername' : 'खाता बही का नाम',
  'ledgerfolionum' : 'लेजर फोलियो नं.',
  'ledgerfolioname' : 'लेजर फोलियो नाम',
  'ledgerfolioitem' : 'लेजर फोलियो आइटम',
  'endusersearch' : 'खोजें',
  'sln' : 'लेजर नंबर चुनें',
  'slfn' : 'लेजर फोलियो नंबर चुनें',
  'slfi' : 'लेजर फोलियो आइटम का चयन करें',
  'selectledgernum' : '--लेजर नंबर चुनें--',
  'selectledgerfolionum' : '--लेजर फोलियो नंबर चुनें--',
  'selectledgerfolioitem' : '--लेजर फोलियो आइटम चुनेंं--',
  'searchbtn' : 'खोजें',
  'ledger' : 'खाता बही',
  'ledgerfolio' : 'लेजर फोलियो',
  'itemcodeplno' : 'आइटम कोड/पीएल नं',
  'itemDesc' : 'आइटम विवरण',
  'stkqty' : 'स्टॉक मात्रा',
  'stkv' : 'शेयर मूल्य',
  'action' : 'कार्रवाई',
  'allocation' : 'आवंटन',
  'weorkorderno' : 'कार्य आदेश क्रमांक',
  'enduserunit' : 'इकाई',
  'euvalue' : 'कीमत',
  'qbi' : 'जारी की जा रही मात्रा (संख्या में)',
  'iwi' : 'आईआरपीएसएम कार्य आईडी',
  'iwd' : 'आईआरपीएसएम कार्य विवरण',
  'recd' : "प्राप्तकर्ता का विवरण",
  'issuetype' : 'विषय वर्ग',
  'adi' : 'जारी करने की वास्तविक तिथि',
  'at' : 'संपदा प्रकार',
  'purpu' : 'प्रयोजन/उपयोग',
  'issuebtn' : 'मुद्दा',
  'wred' : 'वारंटी/समाप्ति तिथि',
  'qdbi' : 'डीएमटीआर की मात्रा जारी की जाएगी',
  'dbq' : 'डीएमटीआर शेष मात्रा',
  'loc' : 'जगह',
  'rf' : 'से प्राप्त',
  'dmtrD' : 'डीएमटीआर विवरण',
  'asd' : 'उपलब्ध स्टॉक विवरण',
  'puru' : 'प्रयोजन/उपयोग',
  'asir' : 'सभी चयन इनपुट आवश्यक है',
  'lficid' : 'लेजर फोलियो का नाम/आइटम कोड/आइटम विवरण',
  'sfi' : 'फोलियो आइटम का चयन करें',
  'pedmnum' : 'कृपया मांग संख्या दर्ज करें',
  'peallocation' : 'कृपया आवंटन दर्ज करें',
  'peworkordernum' : 'कृपया कार्य आदेश संख्या दर्ज करें',
  'peq' : 'कृपया मात्रा दर्ज करें',
  'pewid' : 'कृपया कार्य आईडी दर्ज करें',
  'pewd' : 'कृपया कार्य विवरण दर्ज करें',
  'perd' : 'कृपया रिसीवर विवरण दर्ज करें',
  'pepu' : 'कृपया उद्देश्य/उपयोग दर्ज करें',

  //------ Settings Screen------
  "settingritle" : "सेटिंग",
  'profile' : 'प्रोफ़ाइल',
  'changepin' : 'पिन बदलें',
  'changelogin' : 'लॉगिन बदलें',
  'changelan' : 'भाषा बदलें',
  'confirmtitle' : 'पुष्टि!!',
  'cdesc' : 'क्या आप एप्लिकेशन से लॉगआउट करना चाहते हैं?',
  'wdyes' : 'हाँ',
  'wdno' : 'नहीं',
  'selela' : 'भाषा चुने',
  'endok' : 'ठीक है',

  // -----------Warranty CRN Summary Screen-----------------
  'erstitle' : 'वारंटी सीआरएन सारांश',
  'wcfd' : 'वारंटी दावा: दिनांक से',
  'wct' : 'वारंटी का दावा: को',
  'wcsrcptdatefrom':'प्राप्ति तिथि: से',
  'wrcrcptdateto':'प्राप्ति तिथि: तक',
  'wrcrly':'रेलवे',
  'wrcunittype':'इकाई प्रकार',
  'wrcunitname':'इकाई का नाम',
  'wrcslctdepart':'विभाग का चयन करें',
  'wrcslctuserdepo':'उपयोगकर्ता डिपो का चयन करें',
  'wrcsubcons':'उप परेषिती',
  'wrcvendor':'विक्रेता',

  //------------------------ Helpdesk Screen--------------------------
  'helpdesktitle' : "सहायता केंद्र",
  'qss' : 'किसी भी प्रश्न/सुझाव/समर्थन के लिए',
  'contactus' : 'हमसे संपर्क करें',
  'phone' : 'फ़ोन',
  'email' : 'ईमेल',
  'enow' : 'अभी ईमेल करें',
  'cnow' : 'अब कॉल करें'
};